### ISSUE TITLE
Absolute and tilde paths doesn't work

### ISSUE THREAD

**Issue by vyorkin** [parcel-bundler/parcel#1236]
Related: https://github.com/parcel-bundler/parcel/pull/850#issuecomment-377811893

For example this:
```
require('/assets/logo.png')
```

```
parcel index.html -p 3101
```
installs the "assets" package for me :)

**Comment by DeMoorJasper** [comment]
Disable autoinstall this should throw the correct error u encounter

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vyorkin** [comment]
Try with `--no-autoinstall`, it doesn't attempt to install the `assets` package anymore and I can see the path to image in the output html `http://localhost:3101/logo.png`, but it isn't served by the parcel –  `404 Not Found`

**Comment by DeMoorJasper** [comment]
That's strange is the file being created in the dist directory?

**Comment by vyorkin** [comment]
no it isn't, just checked,
maybe I should provide smth like "minimal reproducible repo" and then open a new issue?

**Comment by DeMoorJasper** [comment]
You can comment the repo here, no need to open a new issue

**Comment by DeMoorJasper** [comment]
Closing due to inactivity and autoinstall has been fixed

**Comment by marcosbozzani** [comment]
I have the same problem.

Minimal reproducible repo: https://github.com/marcosbozzani/parcel-bug-tilde-abs-paths

Just clone the repo, `yarn install` and `yarn tilde` or `yarn slash`

Tilde error: `Cannot resolve dependency './~\style.css'`
Slash error: `Cannot resolve dependency './..\..\..\..\..\..\`

For now, I've patched `Asset.js` and works for me.

I've also created created a PR with tests: https://github.com/parcel-bundler/parcel/pull/1324

**Comment by houd1ni** [comment]
Me too. With ubuntu 18.04, npm 6 and node 9.

The only difference that I use vuejs. And am trying to resolve `import something from '~/foo/bar'` in /abspath/hello.vue.

It simply puts the tilde to the relative path like this: 'cannot resolve in /abspath/~/foo/bar.js'.

The very similar trouble with paths, that begins with a slash.

**Comment by houd1ni** [comment]
is it really a question or a bug? I've done nothing but using a plain parcel to reproduce this in two projects. I even guess, that others just don't use these aliases at all.

**Comment by barneycarroll** [comment]
@houd1ni it's a verified bug, fixed in #1324. It'll be part of the 1.9 release.

**Comment by barneycarroll** [comment]
@DeMoorJasper can we keep this open until the fix is released? I've found tracking this problem really difficult because according to all records it has been a feature for ages, with all associated bug reports / feature requests closed, which gives the misleading impression that it should be usable now.

**Comment by viztor** [comment]
It doesn't seems the issue is fixed in the latest release

**Comment by viztor** [comment]
@DeMoorJasper  please reopen. this is not fixed. it is horrible looking through all the internet for a solution, and found several times it being mentioned as fixed, then after several times recognizing this as my problem, realizing this was never fixed properly in the first place.

**Comment by julianeden** [comment]
This is still not working. Was Parcel 1 abandoned in favor of Parcel 2 development 2 years ago?

**Comment by houd1ni** [comment]
@julianeden  looks like parcel's issues have been abandoned years ago (:
