### ISSUE TITLE
Imported .less files cashed

### ISSUE THREAD

**Issue by preigile** [parcel-bundler/parcel#1520]
# 🐛 bug report

In `styles` folder I created `main.less` and `other.less`. Then I imported the `other` file into `main` by `@import './other'`. Sometimes the included file is updating (after delete `.cache`), sometimes no.

## 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc
```js
{
  "presets": ["env"]
}
```

command: `npx parcel`

## 🤔 Expected Behavior

The page style should update after changes in `other`

## 😯 Current Behavior

but sometimes the changes are not happened

## 💁 Possible Solution

New `.less` files cached after `npx parcel`, so they shouldn't do it

## 🔦 Context

I really want to split styles, don't only js

## 💻 Code Sample

other.less
```less
.container {
  .item {
      color: #7d7eee;
  }
}
```

main.less
```less
@import "./other";
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1 |
| Node             | 10.0.0 |
| npm/Yarn         | 5.6.0 |
| Operating System | macOS High Sierra 10.13.4 |
| less | 3.0.4 |

**Comment by DeMoorJasper** [comment]
Is this fixed in the latest version of parcel?

**Comment by preigile** [comment]
Unfortunately no. I still have this issue. Now I'm using `npx parcel --no-cache` command to refresh my included styles and run it every time when I want to refresh them
