### ISSUE TITLE
Parcel v1.9.0 not working with parcel-plugin-typescript

### ISSUE THREAD

**Issue by scrossan-crown** [parcel-bundler/parcel#1539]
# 🐛 bug report

After I updated to parcel to verson 1.9.0, I get an error when trying to running `parcel index.html` I get the below error.
![image](https://user-images.githubusercontent.com/30405149/41427702-a1c9c264-6fff-11e8-84eb-37e7e5876de9.png)

## 🎛 Configuration (.babelrc, package.json, cli command)
.babelrc
```
{
  "presets": ["env", "react"],
  "plugins": [
    ["transform-runtime", {
      "polyfill": false,
      "regenerator": true
    }]
  ]
}
```

package.json
```
"dependencies": {
    "@types/react": "^16.3.16",
    "@types/react-dom": "^16.0.6",
    "@types/react-redux": "^6.0.2",
    "@types/react-router-dom": "^4.2.7",
    "@types/react-toastify": "^4.0.0",
    "@types/redux-logger": "^3.0.6",
    "@types/redux-thunk": "^2.1.0",
    "react": "^16.4.0",
    "react-dom": "^16.4.0",
    "react-redux": "^5.0.7",
    "react-router-dom": "^4.3.1",
    "react-toastify": "^4.1.0",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "parcel-bundler": "^1.8.1",
    "parcel-plugin-typescript": "^0.7.1",
    "redux-devtools-extension": "^2.13.2",
    "typescript": "^2.9.1"
  }
```

cli command `parcel index.html`

## 🤔 Expected Behavior

I expected the project to bundle just fine like it did in version 1.8.1

## 😯 Current Behavior
The below error is occuring.
![image](https://user-images.githubusercontent.com/30405149/41427702-a1c9c264-6fff-11e8-84eb-37e7e5876de9.png)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |   1.9.0
| Node             |  10.0.0
| npm/Yarn         |  6.0.1
| Operating System |  Windows and Ubuntu

**Comment by DeMoorJasper** [comment]
This appears to be a parcel-plugin-ts bug @fathyb

**Comment by pmurias** [comment]
This problem is very likely caused by a change of the asset constructors signatures

**Comment by fathyb** [comment]
Fixed in fathyb/parcel-plugin-typescript#40

**Comment by jiayihu** [comment]
I'm still having this issue with `parcel-plugin-typescript@1.0.0`
