### ISSUE TITLE
build freeze on 1.9.2

### ISSUE THREAD

**Issue by coffeeowl** [parcel-bundler/parcel#1583]
# 🐛 bug report

build freeze (as reported in https://github.com/parcel-bundler/parcel/issues/1537) still happens, luckily not as often (at least on Heroku) as it was before and there are some errors being thrown

```
⏳  Building assign.js...
(node:31252) UnhandledPromiseRejectionWarning: Error: socket hang up
    at createHangUpError (_http_client.js:313:15)
    at Socket.socketOnEnd (_http_client.js:416:23)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:31252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:31252) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:31218) UnhandledPromiseRejectionWarning: Error: socket hang up
    at createHangUpError (_http_client.js:313:15)
    at Socket.socketOnEnd (_http_client.js:416:23)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:31218) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:31218) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:31218) UnhandledPromiseRejectionWarning: Error: socket hang up
    at createHangUpError (_http_client.js:313:15)
    at Socket.socketOnEnd (_http_client.js:416:23)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:31218) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

nothing happens after that, build process still gets stuck as before.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.2
| Node             | 10.1.0
| npm/Yarn         | 6.1.0
| Operating System | Linux 4.16.13-1-ARCH

**Comment by DeMoorJasper** [comment]
This seems unrelated to any recent updates, this seems to be originating from the hmr websocket

**Comment by coffeeowl** [comment]
I see. still, I definitely observed a build freeze on Heroku (though it was 1.9.0) where of course we don't run parcel in watch mode.

**Comment by coffeeowl** [comment]
BTW, it seems when this HMR problem happens it leaves `.cache` in a bad state, just restarting watch process doesn't help - even though build succeeds, application doesn't load due to some random errors (looks like some garbage code were generated). So, cache has to be removed.

**Comment by DeMoorJasper** [comment]
Would be nice to detect corrupt cache files, not sure how to implement this though (without performance penalty)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sonaye** [comment]
I'm facing the same issue `@1.9.2`, had to add `"prestart": "rm -rf .cache",` as a temp. workaround.

**Comment by coffeeowl** [comment]
And I can confirm that build freeze issue is still present in 1.9.2, happened a couple of times today. Also, corrupted builds happen pretty often, I had to remove .cache on like every 3rd build.

**Comment by DeMoorJasper** [comment]
@coffeeowl Could you create a reproducible example?

**Comment by coffeeowl** [comment]
For freeze or cache issue? Freeze - I don't think so, as for the cache issue - I'll try.

**Comment by DeMoorJasper** [comment]
Doesn't matter we need to fix both anyways

**Comment by Hammster** [comment]
@DeMoorJasper Example Repo: https://github.com/Hammster/parcel-1.9.x-freeze 

This is a reproduction of the bug, it happens when you've got a lot of vue components, maybe this id generally the case when many files get parsed at once.

I can fix it in our project by changing `maxConcurrentCallsPerWorker` to a value between 1 and 3 in this line.

https://github.com/parcel-bundler/parcel/blob/cc6018ebcb6bb068246ef77c0aa2ee227e11c7b4/src/workerfarm/WorkerFarm.js#L13

**Comment by DeMoorJasper** [comment]
Tbh in environments like heroku parcel probably only gets 1 thread, so it should probably not even start using a worker.

**Comment by DeMoorJasper** [comment]
Should be fixed in latest version as workerfarm has been fixed.

**Comment by Muini** [comment]
I personnaly still have the freezing issue...

Windows 10
Parcel v1.9.7 (tried different versions, no results)
Node v8.11.3
npm v6.0.0
yarn v1.7.0

I tried to set variable env PARCEL_MAX_CONCURRENT_CALLS and/or PARCEL_WORKERS to different values, no success. (with and without no cache, no hmr etc)
It's on a vue project, with node-sass too.

I can successfully start the dev (not the build) if I comment most of my includes, then it's building successfully, and I can put them back one by one until I got everything working.

I have a dual boot with a linux (based on ubuntu) and I have the exact same problem. The env is the same except for the node version. So I don't think it's an OS issue.

Should I create a new issue ?

**Comment by tmchng** [comment]
I also continued to have freeze issues and traced the problem to WorkerFarm.js.

There's an option called `warmWorkers` that is hard-coded to `true` inside WorkerFarm.js. My build no longer freezes after I set it to `false`. I have not had the time to investigate why.

I ended up adding the following line to package.json postinstall script so set `warmWorkers` to `false` every time I install parcel:
`sed -i 's/warmWorkers: true/warmWorkers: false/' ./node_modules/parcel-bundler/src/workerfarm/WorkerFarm.js`

**Comment by DeMoorJasper** [comment]
Please feel free to open up a new issue with your findings @tmchng

**Comment by BBlackwo** [comment]
I've got the same issue as @Muini. If I comment the `@import`s on the file it's freezing on, build, then go back and uncomment the `@import`s  and build again I can get it working. 

`warmWorkers: false` didn't fix it for me. Also setting `PARCEL_MAX_CONCURRENT_CALLS` didn't fix it for me.
