### ISSUE TITLE
Express routes conflict with parcel middleware

### ISSUE THREAD

**Issue by nodkrot** [parcel-bundler/parcel#1734]
# ❔ Question

All my api routes (i.e. in the browser `ajax.get('/services')`) are returning generated `index.html` contents as if there is `/*` somewhere. How can this be resolved?

## 🔦 Context

I am trying to setup a server that will host api endpoints and render the client by parcel middleware in dev mode.

## 💻 Code Sample

```js
const app = express()
const bundler = new Bundler('index.html', {})

if (process.env.NODE_ENV === 'production') {
  app.use(compression())
  app.use(express.static(__dirname + '/dist'))
  app.get('/', (req, res) => {
    res.sendFile(path.join(__dirname + '/dist/index.html'))
  })
}

if (process.env.NODE_ENV === 'development') {
  app.use(bundler.middleware())
}

app.get('/services', (req, res) => {
  res.json({ ping: 'pong' })
})

// Tried after api routes, still nothing
// if (process.env.NODE_ENV === 'development') {
//   app.use(bundler.middleware())
// }
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.4
| Node             | 8.9.1
| npm/Yarn         | 6.1.0
| Operating System | macOS

**Comment by DeMoorJasper** [comment]
Parcel takes over the entire scope of the server, however if you register endpoints before parcel it should trigger those first

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nodkrot** [comment]
hmm, looks like it resolved by putting it after api routes. probably did something wrong last time -_-

**Comment by andrerpena** [comment]
I'm still not being able to use the Parcel middleware in together with Apollo Server's middleware
