### ISSUE TITLE
Incomplete refactoring of function names

### ISSUE THREAD

**Issue by jonahsnider** [parcel-bundler/parcel#2107]
# 🐛 bug report

Parcel minimizes JavaScript in script tags by renaming functions, but doesn't change the original function names in fields like `oninput`.

## 🎛 Configuration

`parcel build index.html`

## 🤔 Expected Behavior

Minimize JavaScript and rename `exampleFunction` to `a`. Rename references to `exampleFunction` to `a` as well.

## 😯 Current Behavior

Just minimizes `exampleFunction`, not any references. This causes errors saying how that function doesn't exist.

## 🔦 Context

I defined a function in a script tag that I wanted to refer to later in `oninput` fields on HTML tags. Since this doesn't work, I can't minimize my JavaScript with Parcel.

## 💻 Code Sample

```html
<!DOCTYPE html>
<html>
<head>
  <script>
    function exampleFunction(string) {
      console.log(string.toUpperCase());
    }  
  </script>
</head>
<body>
  <input type="text" oninput="exampleFunction(this.value)">
</body>
</html>
```
Open up the web inspector console and type some characters in the text box.

Now do the same with the result of `parcel build index.html`

Here's the compressed code from parcel (I beautified it):
```html
<!DOCTYPE html>
<html>

<head>
  <script>function o(o){console.log(o.toUpperCase())}</script>
</head>

<body> <input type="text" oninput="exampleFunction(this.value)"> </body>

</html>
```
As you can see, the `oninput` field was left unchanged, causing it to error.

## 🌍 Your Environment

| Software         | Version |
| ---------------- | ---------- |
| Parcel           | 1.10.1|

**Comment by pizzafox** [comment]
Issue is still present in Parcel `v1.12.4`

**Comment by pizzafox** [comment]
Issue is still present.

**Comment by DeMoorJasper** [comment]
@pizzafox I assume this has actually been fixed in Parcel 2 as we now process inline scripts properly

**Comment by pizzafox** [comment]
Issue is still present in Parcel `v2.0.0-nightly.339+1f558665`.

The output has now changed to the following (formatted):

```html
<!DOCTYPE html>
<html>
  <head>
    <script>
      //# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJtYXBwaW5ncyI6IiIsInNvdXJjZXMiOltdLCJzb3VyY2VzQ29udGVudCI6W10sIm5hbWVzIjpbXSwidmVyc2lvbiI6MywiZmlsZSI6ImluZGV4LkhBU0hfUkVGXzA1ZmIzNmVkNWI2YTU1NTFmNWQ2OTk1YmU4OTI2YzE3LmpzLm1hcCJ9
    </script>
  </head>
  <body>
    <input type="text" oninput="exampleFunction(this.value)" />
  </body>
</html>
```

**Comment by devongovett** [comment]
Appears to be fixed in the latest nightlies (as of #6247). We now treat script tags without `type="module"` how the browser does, i.e. top-level variables are globals and won't be renamed or wrapped in a function.
