### ISSUE TITLE
Shared js file and missing style link

### ISSUE THREAD

**Issue by thezealousfool** [parcel-bundler/parcel#2340]
# 🐛 bug report

### package.json
```js
"scripts": {
    "dev": "node build.js",
    "build": "node build.js"
}
```
### build.js
```js
const rimraf = require('rimraf');
const Bundler = require('parcel-bundler');
const Path = require('path');

rimraf(Path.join(__dirname, './dist') , () => {
    console.log('Removed dist folder');
});

if (process.env.NODE_ENV === 'production') {
    rimraf(Path.join(__dirname, './.cache') , () => {
        console.log('Removed cache folder');
    });
}

const entryFiles = [
    Path.join(__dirname, './src/index.html'),
    Path.join(__dirname, './src/index2.html')
];

const bundler = new Bundler(entryFiles);
bundler.on('bundled', (bundle) => {
    console.log("Bundling done");
});
bundler.bundle();
```

### src/index.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width,initial-scale=1,shrink-to-fit=no" name="viewport" />
    <title></title>
</head>
<body>
    <script src="./index.js"></script>
    <h1>Index.html</h1>
</body>
</html>
```

### src/index2.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width,initial-scale=1,shrink-to-fit=no" name="viewport" />
    <title></title>
</head>
<body>
    <script src="./index.js"></script>
    <h1>Index2.html</h1>
</body>
</html>
```

### src/index.js
```js
import './index.css'
```

### src/index.css
```css
body {
    background-color: red;
}
```
### dist/index.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width,initial-scale=1,shrink-to-fit=no" name="viewport">
    <title></title>
<link rel="stylesheet" href="/src.e31bb0bc.css"></head>
<body>
    <script src="/src.e31bb0bc.js"></script>
    <h1>Index.html</h1>
</body>
</html>
```

### dist/index2.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width,initial-scale=1,shrink-to-fit=no" name="viewport">
    <title></title>
</head>
<body>
    <script src="/src.e31bb0bc.js"></script>
    <h1>Index2.html</h1>
</body>
</html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3 |
| Node             | 11.3.0 |
| npm/Yarn         | npm 6.4.1 |
| Operating System |

**Comment by emilniklas** [comment]
I've been digging a bit, and I've found where the bug occurs.

[Here](https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/Bundler.js#L655-L658), the bundler rejects creating a new bundle for the `index.js` asset as a child of `index2.html`, since it's already been created as a child of `index.html`, and therefore is an entry point for the `index.js` bundle created at that point.

I'm not sure how to fix the issue, but at that point, somehow the asset must still be registered on the bundle, so that the lookup [here](https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/packagers/HTMLPackager.js#L27-L31) can find it.

**Comment by cliffasaurus** [comment]
Any updates?

If I'm not mistaken, the current work around is to create an index for each entry point?
`index-main.js` for `index.html`
`index-about.js` for `about.html`

**Comment by codinggirl** [comment]
package any pug files meet the same issue.

**Comment by maximelebreton** [comment]
any news?

Temp solution:
```
src/
├── pages/
│   ├── about.js
│   ├── about.html
│   ├── index.js
│   └── index.html
└── shared.js
```

**src/shared.js**
```
import "./styles.scss";
import "jquery/dist/jquery.slim.js";
import "bootstrap";
```

**src/pages/about.js**
```
import "../shared.js";
```
**src/pages/about.html**
```
<script src="about.js"></script>
```

**src/pages/index.js**
```
import "../shared.js";
```
**src/pages/index.html**
```
<script src="index.js"></script>
```

**Comment by DZakh** [comment]
I have the same issue. The solution that @maximelebreton suggested kind of helped me for now, but I prefer to keep all files on the same layer, so my structure looks like this:
```src/
├── assets/  
│   └── ...
├── index.html
├── index.js
├── page2.html
└── page2.js
```
Where in **index.js** I have all asset imports, and if I want to create some other page, I add **page2.html** and link to an auxiliary **page2.js** file with the only line inside `import './index.js';`.

Unfortunately you need to create the specific js linker file for an every new html page. It may make the **src/** folder kind of messy, but at least urls will stay more obvious.

**Comment by sergeyzwezdin** [comment]
@mischnic The original issue was reported more than a year ago. Any update so far?

**Comment by mischnic** [comment]
@sergeyzwezdin I've just tested this with Parcel 2, it's fixed.

**Comment by sergeyzwezdin** [comment]
@mischnic When it's going to be published?

**Comment by mischnic** [comment]
The current alpha version works as expected.

**Comment by sergeyzwezdin** [comment]
@mischnic ok, but when it will be published as a stable version? I wouldn't like to use alpha.

**Comment by equistx** [comment]
> The current alpha version works as expected.

Which one is it please? I've tried 2.0.0-nightly.85 - not working.

**Comment by mischnic** [comment]
@equistx Please provide a (small) code sample

**Comment by equistx** [comment]
```
├── pages/
│   ├── page1.html
│   ├── page2.html
│   ├── index.js
│   ├── index.scss
```
index.js: `import './index.scss';`
index.scss: `body {background: black;}`
page1.html & page2.html inside body tag: `<script src="index.js"></script>` 
cmd: `parcel pages/*.html`

localhost:1234/page1.html - has black body and css linked inside head tag
localhost:1234/page2.html - has not

**Comment by equistx** [comment]
@mischnic I'm sorry and thank you, my fault, it is working. I've been somehow using wrong version, because I had somehow `parcel` and `parcel-bundle` installed concurrently (not somehow rly, but because there is `parcel-bundle` in docs vs `parcel` in git installation guide - I see the difference now). Of course, every cmd `parcel` command was related to `parcel-bundle`, instead of to `parcel@alpha` one.

**Comment by brettinternet** [comment]
@mischnic Should this work for the `parcel build` command as well?

I get this error when attempting `parcel build src/pages/**/*.pug`.

```
🚨 Build failed.
Error: Bundles must have unique filePaths
```

Using `"parcel": "^2.0.0-alpha.3.2"`.

**Comment by mataslib** [comment]
> Unfortunately I can't use working alpha, since HMR stopped working after I switched from parcel-bundle to parcel. Changes made inside @imported sass files are not detected therefore browser doesn't reload.

After some time, I got back to this. Unfortunately, issue is still there on `2.0.0-nightly.164`. I found out that I was wrong, because changes are actually detected, rebuild happens, but it seems to be some kind of cache issue - when I use `--no-cache`, then it starts working as expected. But downside of this "hotfix" is, that rebuild takes 10x more time than before.

**Comment by mischnic** [comment]
> sass

> to be some kind of cache issue

-> https://github.com/parcel-bundler/parcel/issues/3708

**Comment by matthacksteiner** [comment]
still having the same issue on the last 1.x version

**Comment by azumbrunnen** [comment]
how is it possible that souch a foundational bug that prevents anyone from building multi-page sites haven't been solver in over a year?

**Comment by meodai** [comment]
I also have this issue best work around for me was to load the css as string and append it to the html myself using
`import cssString from ‘bundle-text:./styles.css’`

**Comment by mischnic** [comment]
Your getting this with Parcel 2 as well?

**Comment by meodai** [comment]
@micopc I am using 1.12.4 the latest stable. (just tried with v2 that has a temp problem "Name already registered with serializer")

**Comment by azumbrunnen** [comment]
This indeed helps but the problem remains that if you have two simple documents pointing to one another, it will follow a.href and try to make sense of the other doc and fail.

if…

meodai.html links to home.html
or home.html links to meodai.html

it still messes up the build process.

**Comment by BigPackie** [comment]
#3008

One part of the issue might be connected with including **inline style** in html file/s.  

**Do not include any inline style in your html files!**

**Comment by etrielQ** [comment]
problem still not solved?

**Comment by 0xzim** [comment]
Till now, there is still no specific fix for this issue. Wild

**Comment by devongovett** [comment]
This should already be working in Parcel 2.

**Comment by vchan14** [comment]
any updates? or other works around from having two separate JS files as mentioned by [maximelebreton](https://github.com/maximelebreton) for 1.x version.

**Comment by shasherazi** [comment]
It is unbelievable that a bug this bad still isn't solved even 4 years later.

**Comment by devongovett** [comment]
Please provide a reproduction.

**Comment by shasherazi** [comment]
My bad; I thought this issue was causing me problems. I think it's another problem. I'm creating an issue for that.
