### ISSUE TITLE
When entry file has a shebang, output it in the first line of the bundle

### ISSUE THREAD

**Issue by cprecioso** [parcel-bundler/parcel#2381]
# 🙋 feature request

In UNIX systems, the first line of a script can be a [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) with the path to the interpreter. When the main entry file has this shebang (and optionally when `target: node`), this shebang line could be taken _out of the bundled modules_ and outputted in the first line of the bundle.

## 🤔 Expected Behavior
`hello-world.js`:
```js
#!/usr/bin/env node

console.log("Hello, world!");
```

```sh
$ parcel build -t node hello-world.js
```

`dist/hello-world.js`:
```js
#!/usr/bin/env node

// parcel bundle prologue ...function(require,module,exports) {
console.log("Hello, world!");
// }... parcel bundle epilogue
```

## 😯 Current Behavior
`dist/hello-world.js`:
```js
// parcel bundle prologue ...function(require,module,exports) {
#!/usr/bin/env node
console.log("Hello, world!");
// }... parcel bundle epilogue
```

(which is actually a `SyntaxError`)

## 🔦 Context

I run into this when trying to make executable scripts for node which have all their files already bundled.

**Comment by cprecioso** [comment]
@sintloer  That's great, I'll start using it! Maybe you could copy the shebang of the entry file instead of having to define it in the `package.json`?

However, I still think parcel should have native support for this, especially as the input is a valid node script but the output is as `SyntaxError`.

**Comment by sintloer** [comment]
@cprecioso, Yes, I think Parcel should support shebang natively.
As for my plugin - your idea is really good. I will want to implement it.

**Comment by sintloer** [comment]
@cprecioso, new version of my plugin (1.2.0) supports copy the shebang of the entry file :)

**Comment by DeMoorJasper** [comment]
@sintloer why didn't you contribute this directly to parcel core?
This seems like something that should be in core if detected?

**Comment by sintloer** [comment]
It should be. It's a good idea.
I'll do it.

**Comment by goodmind** [comment]
@sintloer any updates?

**Comment by alexreg** [comment]
No progress still?

**Comment by fvmsantos** [comment]
any updates?

**Comment by mischnic** [comment]
This should be working already: https://github.com/parcel-bundler/parcel/blob/50893a7ec2b1490e6d0a2f5e1f9ab6a8fc57a113/packages/packagers/js/src/DevPackager.js#L236-L238

**Comment by fvmsantos** [comment]
@mischnic  thanks for the answer.
I'm using the latest version of parcel, but it's still not working for me, do I need to do any specific configuration?

**Comment by mischnic** [comment]
You need to make sure Parcel knows that you're build for a Node target, not for the browser. The easiest way to achieve that is adding
```
  "engines": {
    "node": ">=10"
  }
```
to your package.json

**Comment by fvmsantos** [comment]
Nice, worked also using target with node context.
Thanks!
