### ISSUE TITLE
parcel build fails with "semantic.min.css:undefined:undefined: decl.moveTo is not a function"

### ISSUE THREAD

**Issue by devmao** [parcel-bundler/parcel#2505]
# 🐛 bug report

I'm using Semantic-UI-React and the `build` fails. In dev, it's working fine.

In my `index.js`, I'm importing the Semantic CSS file as follow:
```js
import 'semantic-ui-css/semantic.min.css'
```

## 🎛 Configuration (.babelrc, package.json, cli command)

My `.babelrc`:
```js
{
  "presets": ["env", "react"],
  "plugins": [
    "transform-object-rest-spread",
    "transform-class-properties",
    "react-hot-loader/babel"
  ]
}
```

## 🤔 Expected Behavior

The `build` should not failed!

## 😯 Current Behavior

The `build` fails with this error:
```
×  C:\Users\mapu\dev\my\ilapak-hmi-electron\node_modules\semantic-ui-css\semantic.min.css:undefined:undefined: decl.moveTo is not a function
    at C:\Users\mapu\dev\my\ilapak-hmi-electron\node_modules\semantic-ui-css\semantic.min.css:19:919
    at C:\Users\mapu\dev\my\ilapak-hmi-electron\node_modules\semantic-ui-css\semantic.min.css:19:928
    at C:\Users\mapu\dev\my\ilapak-hmi-electron\node_modules\postcss-merge-rules\dist\index.js:246:22
    at C:\Users\mapu\dev\my\ilapak-hmi-electron\node_modules\parcel-bundler\node_modules\postcss\lib\container.js:135:18
    at Rule.each (C:\Users\mapu\dev\my\ilapak-hmi-electron\node_modules\parcel-bundler\node_modules\postcss\lib\container.js:101:16)
    at Rule.walk (C:\Users\mapu\dev\my\ilapak-hmi-electron\node_modules\parcel-bundler\node_modules\postcss\lib\container.js:131:17)
    at C:\Users\mapu\dev\my\ilapak-hmi-electron\node_modules\postcss-merge-rules\dist\index.js:242:18
    at C:\Users\mapu\dev\my\ilapak-hmi-electron\node_modules\parcel-bundler\node_modules\postcss\lib\container.js:239:18
    at C:\Users\mapu\dev\my\ilapak-hmi-electron\node_modules\parcel-bundler\node_modules\postcss\lib\container.js:135:18
    at Root.each (C:\Users\mapu\dev\my\ilapak-hmi-electron\node_modules\parcel-bundler\node_modules\postcss\lib\container.js:101:16)
    at Root.walk (C:\Users\mapu\dev\my\ilapak-hmi-electron\node_modules\parcel-bundler\node_modules\postcss\lib\container.js:131:17)
    at Root.walkRules (C:\Users\mapu\dev\my\ilapak-hmi-electron\node_modules\parcel-bundler\node_modules\postcss\lib\container.js:237:19)
```

## 💁 Possible Solution

A downgrade of Semantic-UI or Parcel(?)

## 🔦 Context

I'm importing Sementic-UI-CSS as described in Sementic-UI [documentation](https://react.semantic-ui.com/usage) 

## 💻 Code Sample

```js
import 'semantic-ui-css/semantic.min.css'
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             | 10.14.0
| npm/Yarn         | 6.4.1
| Operating System | Windows 10
| Sementic-UI | 0.84.0

**Comment by DeMoorJasper** [comment]
Might be a cssnano bug, does it work with `--no-minify`?

**Comment by devmao** [comment]
Yes, works with `--no-minify`. I guess it's a dep issue:

```
`-- parcel-bundler@1.11.0
  +-- cssnano@4.1.8
  | `-- cssnano-preset-default@4.0.6
  |   `-- postcss-merge-rules@4.0.2
  `-- htmlnano@0.1.10
    `-- cssnano@3.10.0
      `-- postcss-merge-rules@2.1.2
```

`htmlnano@0.1.10` uses an old version of `postcss-merge-rules`.

**Comment by DeMoorJasper** [comment]
@devmao would be great if you could experiment a little and update the htmlnano dep manually to test it.

**Comment by devmao** [comment]
The latest `htmlnano` (0.2.2) uses the same `cssnano` (^4.1.8) of  `parcel-bundler`. So, an `htmlnano ` upgrede to 0.2.2 should fix this issue.

**Comment by mischnic** [comment]
@devmao Was this fixed by your PR?

**Comment by JAicewizard** [comment]
This still happens using parcel-bundler `1.12.5`. Even with an empty css file.

inde.html:
```
<!DOCTYPE html><html lang="en"><link rel="stylesheet" href="style.css" /></html>
```
style.css:
```

```

**Comment by KokoDoko** [comment]
Still the same problem here. I can fix it only by using `--no-minify`

**Comment by slavbar** [comment]
> Still the same problem here. I can fix it only by using `--no-minify`

That helped as a quick temporary solution. But that's a hack. We do need minification for production.

**Comment by jedgar1mx** [comment]
Yes, I'm having the same issue.

**Comment by aaroncrawford** [comment]
@AlexMelw  @jedgar1mx 

Was getting the same issue with parcel 1.12.5 and cssnano v5.  Downgraded cssnano to 4.1.11 and it started building.

`npm uninstall cssnano`
`npm i -D cssnano@4.1.11`

Not sure if it will fix anyone else's issue, but worked for us.

**Comment by Daemoneq** [comment]
I lov u bro it works for me

**Comment by slavbar** [comment]
> @AlexMelw @jedgar1mx
> 
> Was getting the same issue with parcel 1.12.5 and cssnano v5. Downgraded cssnano to 4.1.11 and it started building.
> 
> `npm uninstall cssnano`
> `npm i -D cssnano@4.1.11`
> 
> Not sure if it will fix anyone else's issue, but worked for us.

Where did you run those commands?
Inside your current work project or inside the Parcel project?

**Comment by aaroncrawford** [comment]
Run those commands wherever your package.json file is

**Comment by jackie1santana** [comment]
> `npm uninstall cssnano`
> `npm i -D cssnano@4.1.11`

thank you it worked

**Comment by kianbabai** [comment]
> @AlexMelw @jedgar1mx
> 
> Was getting the same issue with parcel 1.12.5 and cssnano v5. Downgraded cssnano to 4.1.11 and it started building.
> 
> `npm uninstall cssnano` `npm i -D cssnano@4.1.11`
> 
> Not sure if it will fix anyone else's issue, but worked for us.

Thank you.
