### ISSUE TITLE
What is the best practice for file name / structure?

### ISSUE THREAD

**Issue by MariuzM** [parcel-bundler/parcel#2741]
When using ParcelJS and running `npm run prod`, it does not account for images being in different directory and thus when loading the page images are not loaded.

So i have background image placed in CSS (src folder) 
`  
background-image: url(../img/cover.png);
`

After Parcel it moves all the files to one main folder but it does not change the cover.png destination. 
`  background-image: url(../cover.ff2eb614.png);
`

For me to fix i would need to remove .
`  background-image: url(./cover.ff2eb614.png);
`

So I'm wandering is there a best practice for these things? So currently my workflow is build and copy all files to my VPS via sFTP

**Comment by mischnic** [comment]
> `background-image: url(../cover.ff2eb614.png);`

This likely related to a recent bug: https://github.com/parcel-bundler/parcel/pull/2740

**Comment by MariuzM** [comment]
And here i thought i was doing something wrong :D

**Comment by mischnic** [comment]
Could you please upgrade to version 1.12.1 or later and try it again? Should be fixed

**Comment by MariuzM** [comment]
Hm still having issues. but maybe not the same as before. I'm using AnimeJS but i'm getting `Uncaught ReferenceError: anime is not defined
`
