### ISSUE TITLE
Asset path in `browserconfig.xml` are not imported

### ISSUE THREAD

**Issue by Spy-Seth** [parcel-bundler/parcel#3145]
# 🐛 bug report

I have these two files:

My `index.html` file:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Hello world</title>

    <!-- Over simplified html file -->

    <meta name="msapplication-config" content="./browserconfig.xml" />
    <meta name="msapplication-TileColor" content="#222222" />
   
    <!-- ... -->
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>

    <script src="./index.js"></script>
  </body>
</html>
```

The content of the `browserconfig.xml`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<browserconfig>
    <msapplication>
        <tile>
            <square150x150logo src="./mstile-150x150.png"/> <!-- This file exist on the filesystem -->
            <TileColor>#222222</TileColor>
        </tile>
    </msapplication>
</browserconfig>
```

## 🤔 Expected Behavior

I expect that the `browserconfig.xml` are parsed at build time. And all the linked resources are in the output build and the path that describe them are rewritten

## 😯 Current Behavior

The `./mstile-150x150.png` file is not outputed in the build (so the path are not rewritten).

## 💁 Possible Solution

Parse and manage the asset in the `browserconfig.xml` files (file used by windows)

**Comment by mischnic** [comment]
This could also be solved by a plugin.

**Comment by mtaylor76** [comment]
Any update on this? This is still a problem as far as I can see.

**Comment by mtaylor76** [comment]
To anyone else with the same problem as me and who stumbles across this bug: you can get parcel to properly import asset paths from `browserconfig.xml` by using [parcel-plugin-browserconfig](https://www.npmjs.com/package/parcel-plugin-browserconfig).

**Comment by Spy-Seth** [comment]
I'm closing this as there is a plugin that solve the issue. Thanks @mtaylor76
