### ISSUE TITLE
Unexpected token ] in JSON

### ISSUE THREAD

**Issue by Olian04** [parcel-bundler/parcel#351]
I get this strange error when I'm trying to use the `react-dates` library. 
```
.../node_modules/react-dates/index.js: Unexpected token ] in JSON 
    at position 364 while parsing near '...ect.assign"],    ],  },    "produ...' 
    in .../node_modules/react-dates/index.js
    at module.exports (.../node_modules/parse-json/index.js:26:19)
    at Object.load (.../node_modules/parcel-bundler/src/utils/config.js:40:12)
    at <anonymous>
```
At first i thought this had to be a problem with `react-dates`, but the guys over there tells me it has to be a parcel related error. Their theses was that it looks like parcel is picking up some `.babelrc` file, and that it then fails when trying to parse it. Problem is I'm using typescript, so i have no idea where that supposed bable file is coming from.

The `react-dates` issue: https://github.com/airbnb/react-dates/issues/907

__Versions:__
npm: 5.5.1
react: 16.2.0
parcel-bundler: 1.2.0

**Comment by ljharb** [comment]
Note that `.babelrc` is published inside `react-dates` itself; that's where the file is coming from. As to why parcel is picking it up - either attempting to require it, or babel-transpiling node_modules - i'm not sure.

**Comment by DeMoorJasper** [comment]
This is a bug with react-dates babelrc, pretty sad they don't see their json is not valid

**Comment by DeMoorJasper** [comment]
This might however be fixed in the new version of Parcel 1.2.1 where we utilise JSON5

**Comment by ljharb** [comment]
Right, it's not required to be JSON; it's JSON5.

However, I'm still not sure why parcel would be interacting with *any* rc file inside node_modules?

**Comment by DeMoorJasper** [comment]
It's something it does to properly process dependencies, but it causes issues from time to time

**Comment by Olian04** [comment]
@DeMoorJasper could you have a look at this https://github.com/uber/react-vis/issues/700#event-1394703772? Could it be that parcel is causing that?
