### ISSUE TITLE
Parcel 2: @parcel/transformer-babel: Support for the experimental syntax 'optionalChaining' isn't currently enabled:

### ISSUE THREAD

**Issue by Banou26** [parcel-bundler/parcel#3917]
# 🐛 bug report

When trying to use a babel proposal, e.g optional chaining, Parcel 2 throws an error

## 🎛 Configuration (.babelrc, package.json, cli command)
`.babelrc`
```js
{
  "plugins": [
    "@babel/plugin-proposal-optional-chaining"
  ]
}
```

```js
{
  "private": true,
  "name": "web",
  "version": "1.0.0",
  "main": "index.js",
  "devDependencies": {
    "@babel/plugin-proposal-optional-chaining": "^7.7.5",
    "parcel": "^2.0.0-alpha.3.2"
  },
  "scripts": {
    "dev": "parcel src/index.html"
  },
  "browserslist": [
    "last 1 Chrome versions"
  ]
}
```

## 🤔 Expected Behavior

Parcel should use the current babelrc config

## 😯 Current Behavior

Parcel throws
```
× @parcel/transformer-babel: Support for the experimental syntax 'optionalChaining' isn't currently enabled
```
## 💻 Code Sample

```js
const foo = undefined?.bar
```

**Comment by mischnic** [comment]
Works for me with the package.json you posted and doing a fresh `yarn install`.

```json
{
  "scripts": {
    "build": "parcel build index.js"
  },
  "devDependencies": {
    "@babel/plugin-proposal-optional-chaining": "^7.7.5",
    "parcel": "^2.0.0-alpha.3.2"
  }
}

```

Maybe some dependency in your lockfile is outdated?

---
Unrelated:

> "main": "index.js",
> "dev": "parcel src/index.html"

The input and output file type don't match up.

**Comment by Banou26** [comment]
It seems the problem only occurs in my lerna monorepo, if i `yarn install && yarn dev` outside of it, everything works but once in it, it throws that error

**Comment by mischnic** [comment]
Indeed

**Comment by mischnic** [comment]
```
3917-babel-proposal
├── package.json // {"workspaces": ["test"]}
├── test
│   ├── .babelrc // {"plugins": ["@babel/plugin-proposal-optional-chaining"]}
│   ├── index.js
│   └── package.json
└── yarn.lock
```

The babelrc isn't used because this to babel 
https://github.com/parcel-bundler/parcel/blob/92fd22f262eb6f301bfd00769066a8f6fb2ef1e4/packages/transformers/babel/src/config.js#L36-L40
doesn't find it.

> By default, Babel will only search for .babelrc files within the "root" package because otherwise Babel cannot know if a given .babelrc is meant to be loaded, or if it's "plugins" and "presets" have even been installed, since the file being compiled could be inside node_modules, or have been symlinked into the project.
https://babeljs.io/docs/en/options#babelrcroots

cc @padmaia might have more insight into the babel config resolution.
```js
> require("@babel/core").loadPartialConfig({
... 	filename: '.../3917-babel-proposal/test/index.js',
... 	cwd:'.../3917-babel-proposal/test/',
... 	root:'.../3917-babel-proposal'
... })
PartialConfig {
  options: {
    filename: '.../3917-babel-proposal/test/index.js',
    cwd: '.../3917-babel-proposal/test',
    root: '.../3917-babel-proposal',
    babelrc: false,
    configFile: false,
    passPerPreset: false,
    envName: 'development',
    plugins: [],
    presets: []
  },
  babelignore: undefined,
  babelrc: undefined,
  config: undefined
}
```
To explicitly allow them with `babelrcRoots`:
```js
> require("@babel/core").loadPartialConfig({
... 	filename: '.../3917-babel-proposal/test/index.js',
... 	cwd:'.../3917-babel-proposal/test/',
... 	root:'.../3917-babel-proposal',
... 	babelrcRoots: [".","./test"]
... })
PartialConfig {
  options: {
    filename: '.../3917-babel-proposal/test/index.js',
    cwd: '.../3917-babel-proposal/test',
    root: '.../3917-babel-proposal',
    babelrcRoots: [ '.', './test' ],
    babelrc: false,
    configFile: false,
    passPerPreset: false,
    envName: 'development',
    plugins: [ [ConfigItem] ],
    presets: []
  },
  babelignore: undefined,
  babelrc: '.../3917-babel-proposal/test/.babelrc',
  config: undefined
}
```

**Comment by noahehall** [comment]
had this issue with parcel "parcel": "1.12.4",

upgrading to alpha saved my afternoon

**Comment by xfoxfu** [comment]
I have a similar problem, when using parcel v2 alpha3 with a TypeScript file, the optional chaining operator also raises the error above. I think TypeScript files compiled by `tsc` does not emit an optional chaining operator.

**Comment by astegmaier** [comment]
@mischnic - I think that @Banou26's original issue was fixed by #4132, so it might be okay to close this.

For @xfoxfu's issue, it looks like there's some discussion in #4085 about how to make typescript features like class properties (and presumably also optional chaining) compile out-of-the-box.

@noahehall - if you use a nightly build that contains #4132 (post, I would expect your scenario to work) _as long as your child package babel config is a `babelrc` file (_not_ a `babel.config.json` file). See [this matrix ](https://astegmaier.github.io/parcel2-monorepo-babel-bug/parcel-goals#solution-scenarios)for an explanation of what is expected to work.

**Comment by xfoxfu** [comment]
@astegmaier exactly. I have found out that latest `@babel/preset-typescript` works out-of-the-box, if there are no decorators. Maybe the project can depend on it with a not-fixed version.

**Comment by IljaDaderko** [comment]
I think this discussion I opened is related. I don't have any babel config with optional chainig (should I, or is it supported out of the box?) But I am also within monorepo:

```
packages/
  app/
      package.json - with parceel config
package.json - with parcel dev dependency
```

**Comment by devongovett** [comment]
I think the original issue here is fixed by #4133 

As for when you need a babel plugin or not, that's up to what's included in babel-preset-env.

**Comment by lukejagodzinski** [comment]
This is still not fixed. I'm trying to use:

```json
{
  "plugins": ["@babel/plugin-proposal-nullish-coalescing-operator"]
}
```

in my `.babelrc` and it shows `@parcel/transformer-babel: Support for the experimental syntax 'jsx' isn't currently enabled` error.

When I move `.babelrc` to main monorepo directory then it starts working. It also work when I remove `.babelrc` file all together. So is it necessary to have Babel config or not? Do I just need to install plugin packages and it will pick it automatically without configuring?

**Comment by mischnic** [comment]
Are you using React? Parcel 2 applies `preset-react` by default in a React project if you don't have a babel config. You'll need add it explcitily if you add a babelrc

**Comment by lukejagodzinski** [comment]
@mischnic Yep I'm using React. I wasn't using .babelrc config for that project. And wanted to add support for the experimental feature, so I thought that when I add .babelrc with just this plugin then Parcel 2 will automatically detect it. But apparently it's enough to add it to the packages.json and it will be picked. So no need for me to add .babelrc. I don't know if it's described in docs or not but it was a little bit confusing for me. I will probably end up using .babelrc anyway as I need the same config for Jest.

**Comment by mischnic** [comment]
>  But apparently it's enough to add it to the packages.json and it will be picked.

Nullish coalescing should be supported by a recent `@babel/preset-env` version, maybe you just need to bump your deps. Adding the dep might have caused that, Parcel doesn't determine the babel config packages on your dependencies.

It would be documented here once we get around to it https://v2.parceljs.org/languages/babel/...
