### ISSUE TITLE
Cannot read property 'port' of null

### ISSUE THREAD

**Issue by heyMP** [parcel-bundler/parcel#4]
I installed parcel-bundler globally.  When I run `parcel index.html` I get the following error.

```
Server running at http://localhost:1234
🚨  Cannot read property 'port' of null
    at new HMRServer (/Users/scienceonlineed/.config/yarn/global/node_modules/parcel-bundler/lib/HMRServer.js:8:43)
    at Bundler.start (/Users/scienceonlineed/.config/yarn/global/node_modules/parcel-bundler/lib/Bundler.js:177:18)
    at /Users/scienceonlineed/.config/yarn/global/node_modules/parcel-bundler/lib/Bundler.js:130:15
    at next (native)
    at step (/Users/scienceonlineed/.config/yarn/global/node_modules/parcel-bundler/lib/Bundler.js:3:191)
    at /Users/scienceonlineed/.config/yarn/global/node_modules/parcel-bundler/lib/Bundler.js:3:437
    at /Users/scienceonlineed/.config/yarn/global/node_modules/parcel-bundler/lib/Bundler.js:3:99
    at Bundler.bundle (/Users/scienceonlineed/.config/yarn/global/node_modules/parcel-bundler/lib/Bundler.js:160:7)
    at Bundler.serve (/Users/scienceonlineed/.config/yarn/global/node_modules/parcel-bundler/lib/Bundler.js:615:10)
    at Command.bundle (/Users/scienceonlineed/.config/yarn/global/node_modules/parcel-bundler/bin/cli.js:67:13)
```

### Mac
```
Node version: v6.11.5
Mac version: 10.12.5
```

### Dockerfile:
```
FROM node:6.11.4
RUN npm install -g parcel-bundler
USER node
WORKDIR /home/node/html
CMD [ "parcel", "index.html" ]
EXPOSE 1234
```

**Comment by devongovett** [comment]
hmm, could be a node v6 thing... seems to work for me on v8.

**Comment by TheLarkInn** [comment]
@devongovett node 6 being current LTS, you'd probably want to at least add the minimum engines value for so that it's obvious for people that they can't use it. Just 2 cents :-D

**Comment by jpsc** [comment]
@TheLarkInn you mean 8 right?
@devongovett why you offer a babel-ed version of `Bunder` for 6? Why not only support 8 with only async ?

**Comment by devongovett** [comment]
it should be supported, just a bug. Someone want to look into what the API difference is? :D

**Comment by bigtunacan** [comment]
Same issue running `node v6.8.1` on Mac `10.12.6`

**Comment by ThatToti** [comment]
the same problem in node version ```v6.9.5```

**Comment by devongovett** [comment]
Should be fixed by bab5ff459efd6452cc947b76de5d6465b5003ddb. Will go out in the next release.

**Comment by devongovett** [comment]
Released in v1.0.2.

**Comment by danielcaldas** [comment]
Is this fixed? I installed version `v1.1.0` and the problem still exists for node version `v6.9.5`, I then upgraded node to `v8.9.0` and it started working as you can see in the picture below.

<img width="1440" alt="screen shot 2017-12-09 at 16 29 14" src="https://user-images.githubusercontent.com/11733994/33797351-57340190-dcfe-11e7-9647-ec117575309d.png">

**Comment by davidnagli** [comment]
@danielcaldas What version of Parcel are you using?

**Comment by danielcaldas** [comment]
I wasn't clear above. I installed parcel `v1.1.0`.l

**Comment by davidnagli** [comment]
Whoops sorry that was a dumb question 😂 

Can you please send a zip file with your setup or post an example repo so I can try to reproduce the issue?

**Comment by davidnagli** [comment]
![screen shot 2017-12-09 at 8 35 32 pm](https://user-images.githubusercontent.com/6759650/33801178-869a2168-dd20-11e7-9e7a-35ee76606036.png)
I ran it on a super minimal example and it worked perfectly (using `Node v6.9.5`)

**Comment by danielcaldas** [comment]
Hey @davidnagli sorry for the false alarm was running `parcel` with a global version (`v1.0.1`)! Tried with `parcel` inside `node_modules/bin` and it's working fine with node `v6.9.5`! Thanks

<img width="1431" alt="screen shot 2017-12-10 at 17 41 22" src="https://user-images.githubusercontent.com/11733994/33807613-7314ab16-ddd1-11e7-9aaf-819e42381e12.png">

**Comment by davidnagli** [comment]
yay! Glad you got it to work :)
