### ISSUE TITLE
"Name already registered with serializer" with parcel@next

### ISSUE THREAD

**Issue by Xiphe** [parcel-bundler/parcel#4064]
# 🐛 bug report

When I run `parcel build` I receive a "Name already registered with serializer" error

## 🎛 Configuration (.babelrc, package.json, cli command)

Blank project with yarn2#[pnp](https://next.yarnpkg.com/features/pnp) and parcel@next

## 🤔 Expected Behavior

No error while building

## 😯 Current Behavior

```
/yarnparcel/.yarn/cache/@parcel-core-npm-2.0.0-nightly.65-a3573223f8-1.zip/node_modules/@parcel/core/lib/serializer.js:28
    throw new Error('Name already registered with serializer');
    ^

Error: Name already registered with serializer
    at registerSerializableClass (/yarnparcel/.yarn/cache/@parcel-core-npm-2.0.0-nightly.65-a3573223f8-1.zip/node_modules/@parcel/core/lib/serializer.js:28:11)
    at Object.<anonymous> (/yarnparcel/.yarn/$$virtual/@parcel-package-manager-virtual-dab9d78bc4/0/cache/@parcel-package-manager-npm-2.0.0-nightly.67-6d59c584b3-1.zip/node_modules/@parcel/package-manager/lib/Npm.js:82:37)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.module_1.Module._load (/yarnparcel/.pnp.js:24084:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/yarnparcel/.yarn/$$virtual/@parcel-package-manager-virtual-dab9d78bc4/0/cache/@parcel-package-manager-npm-2.0.0-nightly.67-6d59c584b3-1.zip/node_modules/@parcel/package-manager/lib/index.js:19:12)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
```

## 💁 Possible Solution

No Idea, sorry ¯\\_(ツ)_/¯

## 🔦 Context

I'm trying to setup a  project with bleeding-edge tooling :)

## 💻 Code Sample

This installs yarn@berry *GLOBALLY*, creates a sample project and produces the error

```
mkdir yarnparcel
cd yarnparcel
npm i -g yarn@berry
yarn init
yarn add parcel@next
echo "<h1>Hello</h1>" > index.html
yarn run parcel build index.html
```
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2
| Node             | 12.13.0
| Yarn         | 2.0.0-rc.27
| Operating System | MacOS 10.14

**Comment by crazy4groovy** [comment]
FYI - I don't see this issue when reverting to `2.0.0-alpha.3.1`

**Comment by Xiphe** [comment]
@crazy4groovy thanks for the feedback! I do get the same error on `2.0.0-alpha.3.1` 

```
mkdir yarnparcel
cd yarnparcel
npm i -g yarn@berry
yarn init
yarn add parcel@2.0.0-alpha.3.1
echo "<h1>Hello</h1>" > index.html
yarn run parcel build index.html
```

**Comment by Xiphe** [comment]
I find it odd that the error comes from a nightly build. Seems as if the sub-packages are not pinned to the `@next` version but use the `@nightly` ?!

```
$ yarn why @parcel/core
└─ parcel@npm:2.0.0-alpha.3.2
   └─ @parcel/core@npm:2.0.0-nightly.65 (via npm:^2.0.0-alpha.3.2)
```

**Comment by chellman** [comment]
I saw this problem as well, solved by deleting the node_modules folder and reinstalling.  Who needs a scalpel when you can use a sledgehammer?

**Comment by mischnic** [comment]
(PnP isn't supported just yet: https://github.com/parcel-bundler/parcel/pull/3582)

**Comment by fregante** [comment]
I also had this problem seemingly without reason. My project is almost empty.

For anyone else who arrives here, try deleting the `.cache` folder in your project as well.

**Comment by talkingtab** [comment]
Using npm to install parcel 2 instead of yarn fixes this for me with 2.0.0-alpha.3.2
```
npm install parcel@next
```

**Comment by YassienW** [comment]
Migrating from parcel 1, same error. Project has nothing but an html file.

**Comment by pojntfx** [comment]
Same problem with Yarn V2.

**Comment by pojntfx** [comment]
Just tried with #3582 and `yarn add -D parcel@2.0.0-nightly.225` - still doesn't work.

**Comment by brandon-pereira** [comment]
Deleting node_modules and re-installing worked for me.

**Comment by mischnic** [comment]
Can someone help me reproduce this with Yarn 2? Seems to work for me:
```sh
niklas@nmb:berry $ yarn set version berry
Resolving berry to a url...
Downloading https://github.com/yarnpkg/berry/raw/master/packages/berry-cli/bin/berry.js...
Saving it into /Users/niklas/Desktop/berry/.yarn/releases/yarn-berry.js...
Updating /Users/niklas/Desktop/berry/.yarnrc.yml...
Done!
niklas@nmb:berry $ yarn init
{
  name: 'berry'
}
$ yarn add -D parcel@nightly
...
➤ YN0000: Done with warnings in 35.11s
$ echo "<h1>Hello</h1>" > index.html
$ yarn parcel index.html
ℹ️ Server running at http://localhost:1234
✨ Built in 1.01s
```

**Comment by brandon-pereira** [comment]
I'm getting this on my server now. I can help debug if needed. I'm running node v12.16.2 on Ubuntu 18.04.2 LTS

**Comment by pojntfx** [comment]
@mischnic Just tried to reproduce your commands on my system (macOS Catalina), the error seems to have been fixed!

<img width="697" alt="Screen Shot 2020-04-20 at 00 27 36" src="https://user-images.githubusercontent.com/28832235/79701482-be282600-829d-11ea-9fea-67e83c67a8d3.png">

**Comment by Banou26** [comment]
This error happens for me, while being on yarn v`1.22.0`, `^2.0.0-nightly.227`.

Tried clearing all node_modules, ect, it's pretty inconsistent, i have one repo with the same parcel version that has the bug, and another one that doesn't have the bug.

**Comment by mischnic** [comment]
This happens when there are have two instances of `@parcel/fs`, `@parcel/package-manager` or `@parcel/workers` that are loaded at the same time when running Parcel.

**Comment by Banou26** [comment]
Shouldn't we re-open this then ?

**Comment by YassienW** [comment]
@mischnic and is there a workaround?

**Comment by mischnic** [comment]
I'm asking once again: 

> Can someone help me reproduce this?

**Comment by steelcracker** [comment]
I was getting this issue after trying to switch from parcel-v1 to parcel-v2.
Deleting node_modules and reinstalling didn't help (using npm).
Deleting node_modules _as well as_ `package-lock.json` did.

**Comment by huw** [comment]
I was migrating from `nodeLinker: node-modules` to PnP, both in yarn v2. The following didn't work:

- Blowing away `node_modules` folders that were sitting around
- Blowing away `yarn.lock`
- Blowing away `.yarn/cache`
- Blowing away `.yarn/cache` and `yarn.lock`

The following did work:

- Blowing away `.yarn` entirely, as well as `yarn.lock` and `.yarnrc.yml`, then just completely reinstalling yarn v2 (and plugins) and re-adding all my packages. I probably also did a VS Code window reload somewhere in there too.

I'm thinking it might be in `.yarn/build-state.yml`, perhaps, which has diffs after reinstalling everything.

**Comment by pittst3r** [comment]
@mischnic I believe this occurs when you are building your app with `parcel@2` and one of your app's dependencies has a dependency on `parcel-bundler@1`. In my particular scenario, I have `parcel@2.0.0-beta.1` to build my app and `parcel-bundler@1.12.4` as a dependency of one of my app's dev dependencies.

**Comment by marc2332** [comment]
@pittst3r You are absolutely right. I removed a dev dependency which relies in parcel@1 and it worked.

**Comment by jupl** [comment]
Unfortunately I'm getting this error when I use Yarn 2 with the ` nodeLinker: node-modules` to still generate `node_modules` as I have other dependencies that are not PnP ready.

**Comment by fawmi** [comment]
This happened to me after migrating from 1 to 2. If someone is interested, I can help reproduce it.

**Comment by jjenzz** [comment]
I'm getting this same error. To reproduce:

```jsx
{
  "name": "test",
  "main": "dist/index.js",
  "scripts": {
    "build": "parcel build src/index.js"
  },
  "devDependencies": {
    "parcel": "next"
  }
}
```

My `src/index.js` contains the following:

```javascript
function foo() {
  console.log('foo');
}

foo();
```

Then I run:

```jsx
yarn set version berry
```

I updated my `yarnrc.yml` to use `node_modules` instead of PnP:

```yml
nodeLinker: node-modules
yarnPath: ".yarn/releases/yarn-berry.cjs"
```

Then `yarn` and `yarn build`.

Same happens with nightly build.

**Comment by lucksp** [comment]
> This happened to me after migrating from 1 to 2. If someone is interested, I can create a public reproducible repo.
> 
> But it is really simple:
> Order of uninstalling 1 and installing 2 is important here.
> When upgrading from 1 to 2, you should first uninstall 1 and then install version 2.
> 
> ```
> // Wrong, this causes the error
> npm install -D parcel@next 
> npm uninstall -s parcel-bunder
> ```
> 
> ```
> // Correct, this will work
> npm uninstall -s parcel-bunder
> npm install -D parcel@next 
> ```
> 
> Deleting package-lock.json and node_modules also fixes the problem

Anyone running into this issue should follow this.

**Comment by jjenzz** [comment]
@lucksp what if you're not migrating but creating a new project from scratch, such as my steps above?

**Comment by lucksp** [comment]
I am not running `yarn` or `berry` so i cannot say for sure, but it felt like a conflict of deps.

**Comment by trusktr** [comment]
I'm not using `yarn`. Here's a reproduction: https://github.com/trusktr/solid-jsx-typescript-parcel-starter

```js
git clone git@github.com:trusktr/solid-jsx-typescript-parcel-starter.git
cd solid-jsx-typescript-parcel-starter
git checkout 6054b0326dffde2422714094ff4b69fbb43bb0be # specific commit, in case I update things and it is working in a later commit
npm install
npm start # Error: Name already registered with serializer
```

**Comment by overlisted** [comment]
There might be other reasons, but I fixed it just by deleting `.cache` directory.

**Comment by ocavue** [comment]
@mischnic 

> Can someone help me reproduce this?

Notice that this repo doesn't use Yarn PnP. It uses `nodeLinker: node-modules` in `.yarnrc.yml` to disable PnP and use `./node_modules` to install packages. 

```
sh-3.2$ cd /tmp
sh-3.2$ git clone https://github.com/ocavue/yarn2-parcel2-issue.git
sh-3.2$ cd yarn2-parcel2-issue
sh-3.2$ node -v
v15.5.1
sh-3.2$ yarn -v
2.4.0
sh-3.2$ yarn install
➤ YN0000: Done with warnings in 8s 978ms
sh-3.2$ yarn dev
Error: Name already registered with serializer
    at registerSerializableClass (/private/tmp/yarn2-parcel2-issue/node_modules/@parcel/core/lib/serializer.js:30:11)
    at Object.<anonymous> (/private/tmp/yarn2-parcel2-issue/node_modules/@parcel/core/node_modules/@parcel/fs/lib/NodeFS.js:229:39)
    at Module._compile (/private/tmp/yarn2-parcel2-issue/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (/private/tmp/yarn2-parcel2-issue/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/private/tmp/yarn2-parcel2-issue/node_modules/@parcel/core/node_modules/@parcel/fs/lib/index.js:21:15)
    at Module._compile (/private/tmp/yarn2-parcel2-issue/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
sh-3.2$
```

**Comment by predikdev** [comment]
I tried everything what is in this issue to solve this problem, but it does not work in my case. I am still getting error: **Name already registered with serializer.**

Environment:

- OS: **Windows 10**
- Node.js: **v14.5.0**
- npm: **6.14.5**
- parcel: **^2.0.0-beta.1**

**Comment by retamozo** [comment]
I strongly recommend upgrade your version to `2.0.0-nightly.623`

**Comment by retamozo** [comment]
> I tried everything what is in this issue to solve this problem, but it does not work in my case. I am still getting error: **Name already registered with serializer.**
> 
> Environment:
> 
> * OS: **Windows 10**
> * Node.js: **v14.5.0**
> * npm: **6.14.5**
> * parcel: **^2.0.0-beta.1**

I had EXACTLY the same issue few minutes ago, and what it fixes was  upgrade my version `2.0.0-nightly.623`

**Comment by armandabric** [comment]
I was stuck in an old nightly because of this bug. After removing all my dependencies related to the bundling (parcel, webpack, babel) and few others (storybook related mainly), I succeed to upgrade to the beta2 by adding them one by one at the time.

**Comment by toastal** [comment]
I'm also having this issue now. I've not been able to solve it by deleting `node_modules` and lockfiles. I even tried to clear the v8 cache with

 ```fish
#!/usr/bin/env fish
rm -rf node_modules
rm yarn.lock
rm -rf $XDG_CACHE_DIR/yarn
rm -rf (echo "process.stdout.write(require('os').tmpdir())" | node -)/v8-compile-cache-*
```

which removed the cache, but it didn't help. Setting `set DISABLE_V8_COMPILE_CACHE 1` didn't help either.

**Comment by trasherdk** [comment]
My fix was:

```sh
npm uninstall -s parcel
rm -fr node_modules package-lock.json
```
edit `package.json` adding `"parcel": "*"` to `devDependencies`

```bash 
npm install
```

**Comment by Gerben-T** [comment]
> My fix was:
> 
> ```shell
> npm uninstall -s parcel
> rm -fr node_modules package-lock.json
> ```
> 
> edit `package.json` adding `"parcel": "*"` to `devDependencies`
> 
> ```shell
> npm install
> ```

This worked for me, but instead of adding `"parcel": "*"` i could just run `npm install parcel@next`

**Comment by trasherdk** [comment]
> 
> 
> > My fix was:
> > ```shell
> > npm uninstall -s parcel
> > rm -fr node_modules package-lock.json
> > ```
> > 
> > 
> > edit `package.json` adding `"parcel": "*"` to `devDependencies`
> > ```shell
> > npm install
> > ```
> 
> This worked for me, but instead of adding `"parcel": "*"` i could just run `npm install parcel@next`

I tried that, but got some error.

**Comment by aminya** [comment]
I hit this error in the following PR when I tried to bundle `@parce/package-manager` or `@parcel/fs`. So I had to declare them as external.
https://github.com/parcel-bundler/parcel/pull/6194#discussion_r620961764

**Comment by jaymorelli96** [comment]
Building with NPM the problem was solved deleting the `node_modules` and the `package-lock.json` and making sure that you don't have the parcel-bundler dependencies as well. 

Many thanks to everyone 💯

**Comment by jackahenderson** [comment]
@mischnic Hi, I am able to reproduce this for Yarn v2 when using the `nodeLinker: "node-modules"` option:

```bash
yarn set version berry
yarn init
echo "nodeLinker: 'node-modules'" >> .yarnrc.yml
yarn add -D parcel@nightly
echo "<h1>Hello</h1>" > index.html
yarn parcel index.html
```

Replacing line 44 of `serializer.js` where the error is thrown with a `console.log(name);` prints:
```
2.0.0-nightly.674+71b3b935:NodeFS
2.0.0-nightly.674+71b3b935:MemoryFS
2.0.0-nightly.674+71b3b935:WorkerFS
2.0.0-nightly.674+71b3b935:Stat
2.0.0-nightly.674+71b3b935:File
2.0.0-nightly.674+71b3b935:Directory
2.0.0-nightly.674+71b3b935:OverlayFS
ℹ️ Server running at http://localhost:1234
✨ Built in 69ms
```
and starts an apparently working server, but I didn't test it that thoroughly.

**Comment by mischnic** [comment]
Try using `yarn set version from source` because the fix for https://github.com/yarnpkg/berry/issues/2500 wasn't released yet

**Comment by jackahenderson** [comment]
> Try using `yarn set version from source` because the fix for [yarnpkg/berry#2500](https://github.com/yarnpkg/berry/issues/2500) wasn't released yet

Amazing, this was just the trick, thankyou!

**Comment by aladdin-add** [comment]
should be `yarn set version from sources` 😄

**Comment by hec9527** [comment]
> There might be other reasons, but I fixed it just by deleting `.cache` directory.

ye, is work.   with parcel@2.0.0-beta.3.1

**Comment by lennon03** [comment]
I'm having the same problem on npm, but not on `2.0.0-beta.3.1` i think you should close the issue

**Comment by Andrew-Dyachenko** [comment]
I have the same error regarding version `2.0.0-nightly.714`
But at the version `2.0.0-beta.3.1` build is ok, but I still need the `2.0.0-nightly.714` version to try to work around the floating bug https://github.com/parcel-bundler/parcel/issues/4145 and some other floating bugs like: 

```bash
[14:16:24] :	 [Step 3/5] Error: Command failed: parcel build templates/partials/header.pug               --dist-dir ./build/zfx --public-url /wp-content/themes/zfx/assets --no-scope-hoist --no-source-maps
[14:16:24] :	 [Step 3/5]     at checkExecSyncError (child_process.js:640:11)
[14:16:24] :	 [Step 3/5]     at execSync (child_process.js:676:15)
[14:16:24] :	 [Step 3/5]     at Object.<anonymous> (/src/build-docker.js:12:1)
[14:16:24] :	 [Step 3/5]     at Module._compile (internal/modules/cjs/loader.js:1068:30)
[14:16:24] :	 [Step 3/5]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
[14:16:24] :	 [Step 3/5]     at Module.load (internal/modules/cjs/loader.js:933:32)
[14:16:24] :	 [Step 3/5]     at Function.Module._load (internal/modules/cjs/loader.js:774:14)
[14:16:24] :	 [Step 3/5]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
[14:16:24] :	 [Step 3/5]     at internal/main/run_main_module.js:17:47 {
[14:16:24] :	 [Step 3/5]   status: null,
[14:16:24] :	 [Step 3/5]   signal: 'SIGSEGV',
[14:16:24] :	 [Step 3/5]   output: [ null, null, null ],
[14:16:24] :	 [Step 3/5]   pid: 23,
[14:16:24] :	 [Step 3/5]   stdout: null,
[14:16:24] :	 [Step 3/5]   stderr: null
[14:16:24] :	 [Step 3/5] }
[14:16:24] :	 [Step 3/5]  [0m [91mnpm ERR! code ELIFECYCLE
[14:16:24] :	 [Step 3/5]  [0m [91mnpm  [0m [91mERR! errno [0m [91m 1
[14:16:24] :	 [Step 3/5]  [0m [91mnpm ERR! main-site@1.16.0 build-docker: `node build-docker.js`
[14:16:24] :	 [Step 3/5] npm  [0m [91mERR! Exit status 1
[14:16:24] :	 [Step 3/5] npm [0m [91m ERR! 
[14:16:24] :	 [Step 3/5]  [0m [91mnpm ERR! Failed at the main-site@1.16.0 build-docker script.
[14:16:24] :	 [Step 3/5]  [0m [91mnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[14:16:24] :	 [Step 3/5]  [0m [91m
[14:16:24] :	 [Step 3/5]  [0m [91mnpm ERR! A complete log of this run can be found in:
[14:16:24] :	 [Step 3/5] npm ERR!     /root/.npm/_logs/2021-06-09T13_16_24_204Z-debug.log
```

**Comment by Andrew-Dyachenko** [comment]
Anyone who also builds a project by setting multiple entry points using Parcel 2 in docker and catches various float errors - try increasing the docker memory, like that:
`docker build -t main-site . --no-cache --memory='1024M'`

**Comment by Andrew-Dyachenko** [comment]
NOPE.
Although my previous advice on expanding docker memory works to fix unexpected build interruption, but when I try to install any other version than `2.0.0-beta.3.1` I get the same error:
```bash
MacBook-Pro-Andrey:client andrew$ npm run build-wp

> main-site@1.16.0 build-wp /Users/andrew/Sites/main-site/src/client
> node build-wp.js

Error: Name already registered with serializer
    at registerSerializableClass (/Users/andrew/Sites/main-site/src/client/node_modules/@parcel/core/lib/serializer.js:30:11)
    at Object.<anonymous> (/Users/andrew/Sites/main-site/src/client/node_modules/@parcel/core/node_modules/@parcel/fs/lib/NodeFS.js:229:39)
    at Module._compile (/Users/andrew/Sites/main-site/src/client/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/Users/andrew/Sites/main-site/src/client/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/andrew/Sites/main-site/src/client/node_modules/@parcel/core/node_modules/@parcel/fs/lib/index.js:21:15)
    at Module._compile (/Users/andrew/Sites/main-site/src/client/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
child_process.js:655
    throw err;
    ^

Error: Command failed: parcel build templates/partials/header.pug               --dist-dir ../wordpress/wp-content/themes/zfx/assets/ --public-url /wp-content/themes/zfx/assets --no-optimize
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at Object.<anonymous> (/Users/andrew/Sites/main-site/src/client/build-wp.js:12:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 7875,
  stdout: null,
  stderr: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! main-site@1.16.0 build-wp: `node build-wp.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the main-site@1.16.0 build-wp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andrew/.npm/_logs/2021-06-15T07_24_38_333Z-debug.log
MacBook-Pro-Andrey:client andrew$
```

**Comment by Andrew-Dyachenko** [comment]
Please fix it, it's unbelievable issue!
I can win it even with nightly builds like `2.0.0-nightly.722`

**Comment by JorgeRodz** [comment]
I have kinda the same issue but using npm. The problem was that I already have Parcel v.1 . So in order to work with the v.2 all I did was:
- uninstall Parcel v.1 from my packages (`npm r parcel-bundler`)
- delete node_modules and install all the packages (`npm install`)

And problem fixed at least for me. Hope this work for someone else.
