### ISSUE TITLE
Cannot find module 'babel-runtime....'

### ISSUE THREAD

**Issue by Topthinking** [parcel-bundler/parcel#408]
parcel verion `1.3.1`

I upgraded the version, and then the error occurred

.babelrc
```json
{
    "presets": [
        "react",
        "es2015",
        "stage-0"
    ],
    "plugins": [
        "babel-plugin-transform-decorators-legacy",
        "babel-plugin-transform-runtime"
    ]
}
```

```error
Uncaught Error: Cannot find module 'babel-runtime/core-js/symbol/to-primitive'
    at newRequire (ccfdca706170b05661250a9fa899b9e8.js:32)
    at localRequire (ccfdca706170b05661250a9fa899b9e8.js:47)
    at Object.require.10 (ccfdca706170b05661250a9fa899b9e8.js:18751)
    at newRequire (ccfdca706170b05661250a9fa899b9e8.js:41)
    at localRequire (ccfdca706170b05661250a9fa899b9e8.js:47)
    at Object.require.3.babel-runtime/core-js/object/define-property (ccfdca706170b05661250a9fa899b9e8.js:22245)
    at newRequire (ccfdca706170b05661250a9fa899b9e8.js:41)
    at localRequire (ccfdca706170b05661250a9fa899b9e8.js:47)
    at Object.require.2.react (ccfdca706170b05661250a9fa899b9e8.js:22316)
    at newRequire (ccfdca706170b05661250a9fa899b9e8.js:41)
```

**Comment by LancerComet** [comment]
+1 for me, but I have tried 1.2.1 and it's still throwing this error.

package.json

```json
"devDependencies": {
    "babel-core": "^6.26.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-stage-2": "^6.24.1",
    "babel-register": "^6.26.0",
    "babel-runtime": "^6.26.0",
    "parcel-bundler": "^1.3.1",
    "parcel-plugin-pug": "^0.2.1",
    "parcel-plugin-vue": "^1.4.0",
    "pug": "^2.0.0-rc.4",
    "stylus": "^0.54.5",
    "typescript": "^2.6.2"
  },
  "dependencies": {
    "vue": "^2.5.13"
  }
```

.babelrc

```json
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["last 3 versions", "> 2%", "ie >= 9", "Firefox >= 30", "Chrome >= 30"]
      },
      "modules": false,
      "loose": true,
      "useBuiltIns": true
    }],
    "stage-2"
  ],
  "plugins": [
    "transform-runtime"
  ],
  "env": {
    "test": {
      "plugins": ["transform-es2015-modules-commonjs"]
    }
  }
}
```

**Comment by LancerComet** [comment]
I give up using `transform-runtime` and use `babel-polyfill` instead. Everything goes well so far. @Topthinking

**Comment by Topthinking** [comment]
@LancerComet 
But I would like to use a  `transform-runtime`, because it will determine what you need to load, selective to load, and not pollution global variables.

**Comment by Alphmega** [comment]
`transform-runtime` not work in parcel +1

**Comment by lc60005457** [comment]
https://github.com/lc60005457/parcel-demo-for-issues/tree/issues-408

**Comment by sabeurthabti** [comment]
Yeah, I am getting this with a module that needs the babel-runtime. 

![screen shot 2017-12-31 at 00 18 15](https://user-images.githubusercontent.com/2606228/34460706-4c3d1d5a-ee0e-11e7-8ba2-6a90d5be13c1.jpg)

**Comment by sabeurthabti** [comment]
I managed to solve this issue by removing the `.cache` folder.

**Comment by devongovett** [comment]
Should be fixed by the above commit in v1.4.1.

**Comment by mfpiccolo** [comment]
Using 1.4.1 I am still getting an error.  The build with `babel-runtime`.  On my large prod react app the build succeeds however when running in the browser I get:

```Uncaught Error: Cannot find module 'babel-runtime/core-js/object/set-prototype-of'
    at newRequire (302803fbf98725642e67506b7792571d.js:33)
    at localRequire (302803fbf98725642e67506b7792571d.js:48)
    at Object.require.33.warning (302803fbf98725642e67506b7792571d.js:19286)
    at newRequire (302803fbf98725642e67506b7792571d.js:42)
    at localRequire (302803fbf98725642e67506b7792571d.js:48)
    at Object.require.13../MemoryRouter (302803fbf98725642e67506b7792571d.js:22063)
    at newRequire (302803fbf98725642e67506b7792571d.js:42)
    at localRequire (302803fbf98725642e67506b7792571d.js:48)
    at Object.require.4.react (302803fbf98725642e67506b7792571d.js:151353)
    at newRequire (302803fbf98725642e67506b7792571d.js:42)
```

That is with this .babelrc:

```
{
  "presets": ["env", "react"],
  "plugins": [
    "syntax-flow",
    "transform-flow-strip-types",
    "transform-decorators-legacy",
    "transform-runtime",
    "transform-object-rest-spread"
  ]
}
```

Similarly, on this test project: 
https://github.com/mfpiccolo/parcel-demo-for-issues/tree/issues-408-mp

The build works and I am getting this error in the console:

`parcel-demo-for-issues.js:73 Uncaught SyntaxError: Unexpected identifier`

Line 73 is: `import _Promise from "babel-runtime/core-js/promise";`

**Comment by Topthinking** [comment]
```shell
parcel -V
1.4.1
```

It still doesn't work

Project 
https://github.com/Topthinking/parcel-react.git

You can execute the following command
```shell
npm install
npm run dva
```

This error will then appear in the console

```error
ccfdca706170b05661250a9fa899b9e8.js:33 Uncaught Error: Cannot find module 'babel-runtime/core-js/symbol/to-primitive'
    at newRequire (ccfdca706170b05661250a9fa899b9e8.js:33)
    at localRequire (ccfdca706170b05661250a9fa899b9e8.js:48)
    at Object.require.52 (ccfdca706170b05661250a9fa899b9e8.js:27050)
    at newRequire (ccfdca706170b05661250a9fa899b9e8.js:42)
    at localRequire (ccfdca706170b05661250a9fa899b9e8.js:48)
    at ccfdca706170b05661250a9fa899b9e8.js:31579
    at Object.require.33.react (ccfdca706170b05661250a9fa899b9e8.js:31580)
    at newRequire (ccfdca706170b05661250a9fa899b9e8.js:42)
    at localRequire (ccfdca706170b05661250a9fa899b9e8.js:48)
    at Object.require.3.babel-runtime/core-js/object/get-prototype-of (ccfdca706170b05661250a9fa899b9e8.js:35724)
```

**Comment by digitaltopo** [comment]
Same issue here using `"parcel-bundler": "1.4.1"`.

It seems that `parceljs` is not finding appropriate babel plugins, or not following babel preset requirements:

```
34097ee3e01edb4356caa2aa46757f82.js:33 Uncaught Error: Cannot find module 'babel-runtime/core-js/object/set-prototype-of'
    at newRequire (34097ee3e01edb4356caa2aa46757f82.js:33)
    at localRequire (34097ee3e01edb4356caa2aa46757f82.js:48)
    at Object.require.48.react (34097ee3e01edb4356caa2aa46757f82.js:18851)
    at newRequire (34097ee3e01edb4356caa2aa46757f82.js:42)
    at localRequire (34097ee3e01edb4356caa2aa46757f82.js:48)
    at Object.require.45../components/Provider (34097ee3e01edb4356caa2aa46757f82.js:21713)
    at newRequire (34097ee3e01edb4356caa2aa46757f82.js:42)
    at localRequire (34097ee3e01edb4356caa2aa46757f82.js:48)
    at Object.require.3.react (34097ee3e01edb4356caa2aa46757f82.js:42688)
    at newRequire (34097ee3e01edb4356caa2aa46757f82.js:42)
    at localRequire (34097ee3e01edb4356caa2aa46757f82.js:48)
    at Object.require.2.react-hot-loader (34097ee3e01edb4356caa2aa46757f82.js:47981)
    at newRequire (34097ee3e01edb4356caa2aa46757f82.js:42)
    at require.112 (34097ee3e01edb4356caa2aa46757f82.js:67)
    at 34097ee3e01edb4356caa2aa46757f82.js:72
```

`.babelrc`
```
{
    "presets": ["env", "react"],
    "plugins": [
        "react-hot-loader/babel",
        "transform-runtime",
        "transform-object-rest-spread"
    ]
}
```

**Comment by mfpiccolo** [comment]
@devongovett Can we reopen this issue?

**Comment by devongovett** [comment]
Ok that was a separate issue, where some node module used ES6 module syntax instead of commonjs, probably via package.json `module` field. We run babel-plugin-transform-es2015-modules-commonjs to convert those to commonjs, but babel was also traversing up to your project to find a babelrc and thus enabling the transform-runtime plugin as well. 1a853be disables babelrc detection when only compiling es6 modules to commonjs. Let me know if it fixes your problem. I'll get a release to npm out shortly.

**Comment by chucksellick** [comment]
I am also getting this issue, any chance of that npm release?

`ba11da78518d78710400d4b7c3148f5c.js:33 Uncaught Error: Cannot find module 'babel-runtime/core-js/object/keys'

**Comment by njtrettel** [comment]
it looks like the fix was released yesterday in [1.5.0](https://github.com/parcel-bundler/parcel/releases/tag/v1.5.0)?
