### ISSUE TITLE
🐛parcel watch fails

### ISSUE THREAD

**Issue by benhutton** [parcel-bundler/parcel#416]
### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": "> 5%",
        "uglify": true
      },
      "useBuiltIns": true
    }]
  ],

  "plugins": [
    "syntax-dynamic-import",
    "transform-object-rest-spread",
    ["transform-class-properties", { "spec": true }]
  ]
}
```

`$ node_modules/.bin/parcel watch app/client/entry.html --out-dir public/dist`

### 🤔 Expected Behavior

When I save a file, it should recompile successfully.

### 😯 Current Behavior

When I save a file, I get the following error:

```
$ node_modules/.bin/parcel watch app/client/entry.html --out-dir public/dist
🚨  Cannot read property 'type' of undefined
    at Bundler.createBundleTree (/home/ben/projects/dg/node_modules/parcel-bundler/src/Bundler.js:373:52) 
    at Bundler.createBundleTree (/home/ben/projects/dg/node_modules/parcel-bundler/src/Bundler.js:412:12) 
    at Bundler.createBundleTree (/home/ben/projects/dg/node_modules/parcel-bundler/src/Bundler.js:412:12) 
    at Bundler.buildQueuedAssets (/home/ben/projects/dg/node_modules/parcel-bundler/src/Bundler.js:245:23)                                                                                                           
    at <anonymous>                                   
    at process._tickCallback (internal/process/next_tick.js:188:7) 
```

### 💁 Possible Solution

I wonder if this is related to https://github.com/parcel-bundler/parcel/issues/294 in some way? I definitely have a setup that is affected by that bug.

### 🔦 Context

I am trying to get HMR working. When I run `parcel watch`, it does the initial compile successfully, but explodes once I save. 

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.3.1 |
| Node             | 8.9.3 |
| npm/Yarn         | 5.5.1/1.2.1 |
| Operating System | Ubuntu 17.10 |

**Comment by devongovett** [comment]
#294 should be fixed by #380. Can you re-test locally using the parcel master branch since the fix isn't released to npm yet?

**Comment by devongovett** [comment]
Now released in v1.4.0. Closing this issue for now, but please reopen if you test and it is still a problem in the latest version.

**Comment by benhutton** [comment]
@devongovett unfortunately, #380 / v1.4.1 did not fix this (though it did fix other problems I was having, so thank you!). Can you please re-open? And let me know what else I should try to debug (or to help others help me debug)?

**Comment by benhutton** [comment]
Not seeing this anymore, so closing.
