### ISSUE TITLE
Unexpected Token export while trying to use tranformer-typescript-tsc on Parcel 2 nightly

### ISSUE THREAD

**Issue by uglycoyote** [parcel-bundler/parcel#4627]
# 🐛 bug report

This is the same error that @shunia mentioned in #4085 when they tried to use `transformer-typescript-tsc`.   I thought I would create a separate issue because #4085 was not really about this problem, it was kind of a side discussion.

@mischnic replied that this problem occurred in the most recent alpha but was fixed in nightly, but I installed `parcel@nightly` yesterday and still have the issue.

```
ℹ️ Server running at http://localhost:1234
🚨 Build failed.
Error: Unexpected token export
/Users/mike/development/parcel-2-test/node_modules/@parcel/ts-utils/src/index.js:2
export * from './FSHost';
^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)
    at Module._compile (internal/modules/cjs/loader.js:684:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at NodePackageManager.load (/Users/mike/development/parcel-2-test/node_modules/@parcel/package-manager/lib/NodePackageManager.js:110:9)
    at NodePackageManager.requireSync (/Users/mike/development/parcel-2-test/node_modules/@parcel/package-manager/lib/NodePackageManager.js:76:17)
    at Module.m.require.id [as require] (/Users/mike/development/parcel-2-test/node_modules/@parcel/package-manager/lib/NodePackageManager.js:97:19)
    at require (internal/modules/cjs/helpers.js:22:18)
```

## 🎛 Configuration (.babelrc, package.json, cli command)

this is using the following in `.parcelrc`

```
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"]
  }
}
```

This is a fairly ordinary dummy test project.  

## 🌍 Your Environment

```
    "@parcel/transformer-typescript-tsc": "^2.0.0-alpha.3"
    "parcel": "^2.0.0-nightly.270",
```

**Comment by mischnic** [comment]
> I installed parcel@nightly yesterday and still have the issue.

It's fixed in the nightly of that package, which you only get in the transformer's nightly:

>  "@parcel/transformer-typescript-tsc": "^2.0.0-nightly.XXX"

**Comment by uglycoyote** [comment]
I see, thanks!

**Comment by TomzBench** [comment]
@mischnic I seem to be using `@parcel/typescript-transformer-tsc@2.0.0-alpha.3` But I am still getting this error. I am using the default nightly config and simply added the typescript-transformer-tsc to the javascript pipeline. Did I miss a step or do this incorrectly?

**Comment by mischnic** [comment]
You should be installing `npm i -D @parcel/transformer-typescript-tsc@nightly`

> (And if I happen to get your attention, ultimately I'm just trying to support lit-element. And have my output for modern browsers only. I can get lit-element components to compile and render, but the web components aren't working as expected. I'm guessing something in the pipelines is mangling something it shouldn't. And since i dont need strong browser support i'm wondering the best way to support lit-element.)

Please open a new issue with a code sample and what exactly isn't working.

**Comment by TomzBench** [comment]
@mischnic 

Thanks,  I managed to get the correct nightly transformer and the Unexpected Token Import error went away. Though the build progressed further it still fails at runtime. I created a minimal repository here: https://github.com/TomzBench/parcel-lit and I created a "Discussion" here: https://github.com/parcel-bundler/parcel/discussions/5970 (as i'm not sure there is an issue but more my usage).

**Comment by gonzoramos** [comment]
Any fixes on this? I can repro the error and since I cannot ```npm i -D @parcel/typescript-transformer-tsc@nightly``` (not found error) I cannot use the tsc compiler... :(

**Comment by mischnic** [comment]
Looks like I had a typo in my previous comment, it's `@parcel/transformer-typescript-tsc`

**Comment by jessabyrne** [comment]
I can also repro the error even after running `npm i -D @parcel/transformer-typescript-tsc@nightly`
I'm on Typescript 4.2.4, it looks like there is a dependency on `typescript@3.0.0`
