### ISSUE TITLE
V2: Cannot read property 'constantViolations' of undefined

### ISSUE THREAD

**Issue by Dreamsorcerer** [parcel-bundler/parcel#4849]
Still trying to build Open Layers as an ES module, using v2. I get this error:

```
🚨 Build failed.
@parcel/packager-js: Cannot read property 'constantViolations' of undefined
TypeError: Cannot read property 'constantViolations' of undefined
    at rename (/home/ubuntu/hacking/teslaclub/maps/openlayers/node_modules/@parcel/scope-hoisting/lib/renamer.js:21:33)
    at Object.generateExports (/home/ubuntu/hacking/teslaclub/maps/openlayers/node_modules/@parcel/scope-hoisting/lib/formats/esmodule.js:119:32)
    at exit (/home/ubuntu/hacking/teslaclub/maps/openlayers/node_modules/@parcel/scope-hoisting/lib/link.js:639:31)
    at NodePath._call (/home/ubuntu/hacking/teslaclub/maps/openlayers/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/home/ubuntu/hacking/teslaclub/maps/openlayers/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/home/ubuntu/hacking/teslaclub/maps/openlayers/node_modules/@babel/traverse/lib/path/context.js:99:8)
    at TraversalContext.visitQueue (/home/ubuntu/hacking/teslaclub/maps/openlayers/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/home/ubuntu/hacking/teslaclub/maps/openlayers/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/home/ubuntu/hacking/teslaclub/maps/openlayers/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/home/ubuntu/hacking/teslaclub/maps/openlayers/node_modules/@babel/traverse/lib/index.js:84:17)
```

package.json looks like:
```
{
  "name": "openlayers",
  "version": "1.0.0",
  "description": "",
  "main": "ol.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "parcel build ol.js"
  },
  "targets": {
    "main": {
      "outputFormat": "esmodule"
    }
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ol": "^6.3.1"
  },
  "devDependencies": {
    "parcel": "^2.0.0-beta.1"
  }
}
```

and ol.js is just:
```
export {Map, View} from 'ol';
export {TileLayer} from 'ol/layer/Tile';
export {OSM} from 'ol/source/OSM';
```

**Comment by kevinweber** [comment]
FYI, this should solve the issue: https://github.com/babel/preset-modules/pull/20. It did for us. You can get the latest version of this dependency using `yarn add @babel/preset-modules@0.1.4` even if Babel's preset-env dependency doesn't reference this version yet. You might need to dedupe this dependency in your yarn.lock file to make sure v0.1.4 is always used over v0.1.3.

**Comment by Dreamsorcerer** [comment]
I removed the node_modules and reran `npm install`. This appears to have installed preset-modules v0.1.4. But, I still get the same error as before.

**Comment by Dreamsorcerer** [comment]
Any chance of a beta2 release, so I can try out this fix?

**Comment by devongovett** [comment]
Probably, but you can try out the nightly releases already. 😉

**Comment by Dreamsorcerer** [comment]
Thanks, I've just given that a go, but Parcel is not doing anything close to what I expected, I must have completely misunderstood something.

With the 2 files shown in the description, I run `npm install` and `npm run build`. The only thing the build seems to do is to rewrite ol.js to:

```
import{OSM as o}from"ol/source/OSM";export{o as OSM};import{TileLayer as r}from"ol/layer/Tile";export{r as TileLayer};import{Map as e,View as m}from"ol";export{m as View,e as Map};
//# sourceMappingURL=ol.js.map
```

What I was expecting is a new file output somewhere, which includes the dependencies, such that I can run elsewhere something like:
```
import("../ol.js").then((ol) => {
    new ol.Map({
        "target": container,
        "layers": [new ol.TileLayer({"source": new ol.source.OSM()})],
        "view": new ol.View({"center": pos, "zoom": 16})
    });
});
```
With `../ol.js` being the resulting file from the build.

What am I misunderstanding about this? Can this be done?

**Comment by mischnic** [comment]
Do this:
```
{
  "name": "openlayers",
  "version": "1.0.0",
  "description": "",
  "module": "dist.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "parcel build ol.js"
  },
  "targets": {
    "module": {
      "includeNodeModules": true
    }
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ol": "^6.3.1"
  },
  "devDependencies": {
    "parcel": "^2.0.0-beta.1"
  }
}
```

Then ol.js won't be rewritten and `dist.js` will contain dependencies as well.
Use `main` instead if you want CommonJS

**Comment by Dreamsorcerer** [comment]
Thanks a lot, I've got a couple of import errors, but that will probably need to be followed up with openlayers. Otherwise, it looks like this is what works for my use case:

```
{
  "name": "openlayers",
  "version": "1.0.0",
  "description": "",
  "main": "ol.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "parcel build index.js"
  },
  "targets": {
    "main": {
        "includeNodeModules": true,
        "outputFormat": "esmodule"
    }
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ol": "latest"
  },
  "devDependencies": {
    "parcel": "nightly"
  }
}
```
