### ISSUE TITLE
Worker attempts to use importScripts() to load CSS

### ISSUE THREAD

**Issue by developit** [parcel-bundler/parcel#5021]
# 🐛 bug report

When using Parcel 2's automatic Worker bundling, the generated code for a Worker attempts to load CSS bundles using `importScripts()`.

This seems to happen despite there being no CSS imports present in the Worker code, and the asset doesn't appear to be referenced anywhere in the generated bundle.

I haven't yet been able to rule out the possibility this has to do with the default TypeScript configuration (`@babel/preset-typescript`) failing to prune style imports.

## 🎛 Configuration

Stock parcel configuration, in dev mode, using TypeScript.

## 🤔 Expected Behavior

Generated Worker bundles should not call `importScripts("xyz.123.css")`.

## 😯 Current Behavior

The first line in a Worker bundle is `importScripts("xyz.123.css")`.

## 💁 Possible Solution

Workers that do not explicitly import CSS resources should not attempt to load CSS. CSS assets depended on by Worker code should be loaded using fetch() instead of importScripts(), or ignored.

## Workaround

I have worked around this for now by patching the `Worker` constructor to inject a wrapper script that overrides `importScripts` so that it ignores `.css` URLs. This works without changing the observable worker loading semantics because `importScripts()` is synchronous.

```js
// first line in entry module, or at least somewhere prior to `new Worker`.
const W = self.Worker;
self.Worker = function (url, options) {
  const code = `importScripts = (function(){return this.apply(self,[].slice.call(arguments).filter(function(x){return !/\\.css$/i.test(x)}))}).bind(importScripts)\nimportScripts(${JSON.stringify(url)})`;
  return new W(URL.createObjectURL(new Blob([code], { type: 'text/javascript' })), options);
};
```

## 🔦 Context

I'm still trying to narrow down exactly when this happens, because there must be a link somewhere that causes the CSS to be associated with the Worker code.

## 💻 Code Sample

**styles.module.scss**

```css
.foo { color: red; }
```

**index.ts**

```ts
import * as styles from './styles.module.scss';
console.log(styles.foo);

new Worker('./worker.ts', { name: 'worker' });
```

**worker.ts**

```ts
console.log('hello world');
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1
| Node             | 12.16.0
| npm/Yarn         | npm@6
| Operating System | MacOS Catalina

**Comment by mischnic** [comment]
Is it possible that the worker imports a file with CSS module imports? Though that does work correctly in a simple case as well...

**Comment by mischnic** [comment]
I just remembered that I have a PR for this already: https://github.com/parcel-bundler/parcel/pull/4884
So a duplicate of https://github.com/parcel-bundler/parcel/issues/4751

But testing that patch on Squoosh, I get a recursive `importScripts` stack overflow error

**Comment by ProLoser** [comment]
I've switched from `next` to `nightly` to fix this problem, however I'm now dealing with other bugs with nightly

**Comment by ProLoser** [comment]
This occurs on `next` but not on `nightly`. Unfortunately when i switched to nightly i ran into a myriad of other problems.

**Comment by ProLoser** [comment]
I see this in javascript, not typescript btw. I'm still debugging this but i have no idea why it occurs. I have a `.jsx` file import a `.js` file that creates the worker. The `.jsx` imports css but the `.js` does not import css.

I have no idea why i still see this bug.

**Comment by mischnic** [comment]
This should have been fixed by https://github.com/parcel-bundler/parcel/pull/5200, which is only contained in the nightly.

It doesn't really make a difference if it's TS or JS.

**Comment by ProLoser** [comment]
Okay this is still happening to me in my custom worker setup (I think). I have actually removed css from my javascript altogether just to avoid dealing with this weird quirk. I am hoping fixing the custom transformer will help fix my own quirks with this bug.
