### ISSUE TITLE
Upgrade to Terser 5

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#5035]
We should upgrade to Terser 5 as Terser 4 will not receive any more updates. Relevant breaking changes:
- `minify()` is now an async function, which isn't a problem for us.

### Solution

1. Update semver range in https://github.com/parcel-bundler/parcel/blob/64ebc3757a7c36432d55ee4d791e96e30dab242f/packages/optimizers/terser/package.json#L28
2. Add await: https://github.com/parcel-bundler/parcel/blob/64ebc3757a7c36432d55ee4d791e96e30dab242f/packages/optimizers/terser/src/TerserOptimizer.js#L42

**Comment by AbderrahimSoubaiElidrissi** [comment]
I will take this

**Comment by AbderrahimSoubaiElidrissi** [comment]
Done https://github.com/parcel-bundler/parcel/pull/5038

**Comment by tbroyer** [comment]
Is there any chance that this gets backported to v1?

Currently, with Safari 14 now being a thing, using `last 2 chrome versions, last 2 firefox versions, last 2 edge versions, last 2 safari versions, last 2 opera versions` as browserslist, nullish coaslescing and optional chaining are no longer transformed, and then `parcel build` fails when minifying because it uses Terser 3.

So, either I use Parcel 1.x and have to include `safari 12` back in my browserslist to make Babel transform those (and probably others, leading to a less optimal code), or I move to `parcel@nightly` to benefit from this change but possibly meeting some bugs, or I move to something else entirely (webpack? rollup?) but nothing seems to use HTML as the entrypoint like Parcel.
For now I chose to _deoptimize_ my code and keep Parcel 1.x, but Parcel 1.x is starting to decay and Parcel 2.x is still not ready so it would be great if there was a stable and maintained solution somewhere.
Having a Parcel 1.13 with an updated Terser would be great.

**Comment by alexburner** [comment]
I'm still not able to use optional chaining in Parcel 2, with a minimal TypeScript setup. 

Terser throws an error when trying to build: 
<img width="483" alt="terser-error" src="https://user-images.githubusercontent.com/409114/109995511-35528700-7cc3-11eb-830c-0c531dd23fdb.png">

Inspecting `package-lock.json`, looks like Parcel is bringing in Terser 4.8.0:
```json
"@parcel/optimizer-terser": {
  "version": "2.0.0-beta.1",
  "resolved": "https://registry.npmjs.org/@parcel/optimizer-terser/-/optimizer-terser-2.0.0-beta.1.tgz",
  "integrity": "sha512-S6uu4Q4L8NV+TQes35dQmHqcA6NaRmQSI0vl75IGSaTJnvnq/M3fvrTUd6Xp4dOt/eLh4UJEH7F01TbO1KFZwg==",
  "dev": true,
  "requires": {
    "@parcel/diagnostic": "2.0.0-beta.1",
    "@parcel/plugin": "2.0.0-beta.1",
    "@parcel/source-map": "2.0.0-alpha.4.13",
    "@parcel/utils": "2.0.0-beta.1",
    "nullthrows": "^1.1.1",
    "terser": "^4.3.0"
  },
  "dependencies": {
    "terser": {
      "version": "4.8.0",
      "resolved": "https://registry.npmjs.org/terser/-/terser-4.8.0.tgz",
      "integrity": "sha512-EAPipTNeWsb/3wLPeup1tVPaXfIaU68xMnVdPafIL1TV05OhASArYyIfFvnvJCNrR2NIOvDVNNTFRa+Re2MWyw==",
      "dev": true,
      "requires": {
        "commander": "^2.20.0",
        "source-map": "~0.6.1",
        "source-map-support": "~0.5.12"
      }
    }
  }
},
```

Am I doing something wrong? Here's my "minimal repro setup"

**index.ts**
```ts
const foo: any = {};
console.log(foo?.bar);
```

**index.html**
```html
<html>
  <body>
    <h1>Hello World</h1>
    <script src="./index.ts"></script>
  </body>
</html>
```

**package.json**
```json
{
  "name": "parcel-2",
  "license": "ISC",
  "scripts": {
    "dev": "parcel index.html",
    "build": "parcel build index.html"
  },
  "browserslist": [
    "last 1 Chrome version",
    "last 1 Safari version",
    "last 1 Firefox version"
  ],
  "devDependencies": {
    "parcel": "2.0.0-beta.1",
    "typescript": "4.2.2"
  },
}
```

Similar to my Parcel 1 comment [here](https://github.com/parcel-bundler/parcel/issues/4458#issuecomment-790085160), the only fix I've found is using `npm-force-resolutions` to pin Terser at version 5.3.2

**Comment by mischnic** [comment]
Use the Parcel `nightly`, not `next`

**Comment by alexburner** [comment]
Ah yep, that fixed it! Thanks @mischnic for the quick response.

Only for my own curiosity: what's the iteration schedule for `parcel@next`? I saw #5038 / #5052 got merged in late August and assumed they'd have made it in by now, but was clearly wrong.

**Comment by mischnic** [comment]
There is no schedule 😬  but there should be a release candidate for Parcel 2 some time soon

**Comment by alexburner** [comment]
Ha that's fair. I'm excited for a release candidate! Any hints what "soon" means? (days, weeks, months)

**Comment by hibou24** [comment]
hello how i can get this change on v1??
