### ISSUE TITLE
Updates to imported scss files are not applied

### ISSUE THREAD

**Issue by jtescher** [parcel-bundler/parcel#5132]
# 🐛 bug report

Updates to imported scss files are not applied.

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```js
{
  "name": "demo",
  "version": "1.0.0",
  "scripts": {
    "start": "parcel serve ./src/index.html",
    "build": "parcel build ./src/index.html"
  },
  "devDependencies": {
    "parcel": "^2.0.0-beta.1",
    "sass": "^1.26.10"
  }
}
```

## 🤔 Expected Behavior

When values in imported scss files e.g. `src/theme.scss` are changed, the output css file should contain the change.

## 😯 Current Behavior

Parcel rebuilds the output css files, but the change is not included. However if after you make the change you update the root `src/app.scss` file, the change _will_ be in the output, so imports are working, but something is wrong when re-computing leaf dependency changes but not root changes.

## 💁 Possible Solution

There is likely an issue in the imported file caching logic. If ` --no-cache` is applied, the change is picked up on page reload but not but by the hot css reloading.

## 💻 Code Sample

src/app.scss
```scss
@import "theme";
```

src/theme.scss
```scss
// e.g. changes to this color will not be applied unless the root app.scss file is changed.
h1 { color: red; }
```

src/index.html
```html
<html>
<head>
  <link rel="stylesheet" href="./app.scss">
</head>
<body>
  <h1>I should change color</h1>
</body>
</html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1
| Node             | v10.22.0
| npm/Yarn         | npm 6.14.6
| Operating System | MacOS 10.15.6

**Comment by DeMoorJasper** [comment]
Pretty sure this is the bug where `includedFiles` does not work yet

**Comment by devongovett** [comment]
Should be fixed by #5132

**Comment by amanteaux** [comment]
I just used the parcel beta 2 version to get rid of this issue, but actually it is still present:
1. First run: after 2 minutes to compile 5 pages... it works as expected (SCSS changes are hot reloaded in the browser)
2. I stop parcel (ctrl+c)
3. Second run: parcel starts almost immediately!
4. I try to update a SCSS file... nothing, the change is not detected anymore

So I end up using the `--no-cache` option... Hopefully I won't need to reload parcel soon. It is getting much much slower than parcel 1 :(

**Comment by megaresp** [comment]
Parcel 2.4.1 and @parcel/transformer-sass 2.5.0 cause this same issue for me. When I add --no-cache to package.json it reloads and sees the imported SCSS files. Ditto on removing. Ditto on making a change to the file style.scss that I load from index.html.

I'm running an Intel mac running OSX. It's a React project. Nothign complex about it. And only one sub-level of SCSS files that are all loaded from style.scss. And all named _<name>.scss.

But, a potential clue. I'm loading them their own folders under scss folder in which style.scss is contained. example: `@import './component/budget';`

I note this bug has been around for a while. Is anybody working on it?
