### ISSUE TITLE
Weird build on Windows

### ISSUE THREAD

**Issue by njtrettel** [parcel-bundler/parcel#576]
**🐛 bug report** 

### 🎛 Configuration

`.babelrc`
```js
{
  "presets": ["env", "react", "es2015", "es2015-loose"],
  "plugins": ["transform-runtime"]
}
```
`package.json`
```js
"scripts": {
  "build": "parcel build index.html --out-dir public/dist --public-url /dist",
  "build-dev": "parcel build index.html --out-dir public/dist --public-url /dist --no-minify"
}
```

### 🤔 Expected Behavior

A browser-compatible React app to be built

### 😯 Current Behavior

The current configuration works fine when building on linux environments. However, when built on Windows, import statements are left in the transpiled code.
I have 2 transpiled `js` files, one created with the above `build-dev` script on linux, and another on Windows. The linux version is free of import statements while the Windows version has these:
```js
import _Object$defineProperty from "babel-runtime/core-js/object/define-property";
import _Object$keys from "babel-runtime/core-js/object/keys";
```
This of course gives an `Unexpected identifier` when trying to run the app.

### 💁 Possible Solution

No idea. Completely stumped.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.2.0
| Node             | 8.9.3
| npm/Yarn         | 5.5.1
| Operating System | Windows 10 Pro / Ubuntu 16.04

Ran on GitBash and windows cmd prompt

**Comment by devongovett** [comment]
That looks like https://github.com/parcel-bundler/parcel/issues/408. That issue is fixed in Parcel 1.4.1 (latest). Please check there!

**Comment by njtrettel** [comment]
Thanks, sorry for the repeat issue

**Comment by njtrettel** [comment]
@devongovett so I'm still getting this issue after upgrading to `1.4.1`. except this time we also tried building with webpack and still get the same unexpected `import`s, so it must be my setup rather than parcel. So I'm still pretty lost. I'm hoping this is because parcel is building my node modules [#448](https://github.com/parcel-bundler/parcel/pull/448). not sure if that is happening in the first place. 

the other alternative is to use `babel-polyfill` i guess, but i'd like to get to the bottom of why (a) the build only breaks on windows and (b) why webpack also breaks this on windows
