### ISSUE TITLE
Parcel 2: "internal error: no content" when using transformer-typescript-tsc

### ISSUE THREAD

**Issue by RVxLab** [parcel-bundler/parcel#5781]
# 🐛 bug report

Compiling TypeScript using `@parcel/transformer-typescript-tsc` causes an error in `@parcel/transformer-babel`:

This does not happen when the transformer is not present.

## 🎛 Configuration (.babelrc, package.json, cli command)

.parcelrc
```json
{
  "extends": "@parcel/config-webextension",
  "transformers": {
    "*.{ts,tsx}": [
      "@parcel/transformer-typescript-tsc"
    ]
  },
  "validators": {
    "*.{ts,tsx}": [
      "@parcel/validator-typescript"
    ]
  }
}

```

tsconfig.json
```json
{
    "compilerOptions": {
        "target": "es5",
        "module": "esnext",
        "lib": [
            "dom",
            "esnext"
        ],
        "jsx": "react",
        "jsxFactory": "h",
        "strict": true,
        "moduleResolution": "node",
        "esModuleInterop": true,
        "skipLibCheck": true,
        "forceConsistentCasingInFileNames": true
    },
    "include": [
        "src/**/*"
    ]
}
```

package.json

```json
{
    "name": "project",
    "version": "1.0.0",
    "description": "",
    "main": "dist/index.html",
    "scripts": {
        "dev": "parcel src/manifest.json --host localhost --target webext-dev",
        "clean": "rm -rf dist/",
        "ext:ff": "web-ext run --source-dir ./dist"
    },
    "targets": {
        "webext-dev": {
            "sourceMap": {
                "inline": true,
                "inlineSources": true
            }
        }
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "devDependencies": {
        "@babel/core": "^7.12.13",
        "@babel/plugin-transform-react-jsx": "^7.12.13",
        "@parcel/config-webextension": "^2.0.0-nightly.2151",
        "@parcel/transformer-typescript-tsc": "^2.0.0-alpha.3",
        "@parcel/validator-typescript": "^2.0.0-alpha.3",
        "parcel": "^2.0.0-beta.1",
        "postcss": "^8.2.4",
        "typescript": "^4.1.3",
        "web-ext": "^5.5.0"
    },
    "dependencies": {
        "preact": "^10.5.12",
        "tailwindcss": "^2.0.2"
    }
}
```

## 🤔 Expected Behavior

It compiled as expected.

## 😯 Current Behavior

It causes the following error:

```
@parcel/transformer-babel: Internal error: missing content
AssertionError [ERR_ASSERTION]: Internal error: missing content
    at UncommittedAsset.getCode (/home/myuser/Projects/project/node_modules/@parcel/core/lib/UncommittedAsset.js:214:27)
    at async babelErrorEnhancer (/home/myuser/Projects/project/node_modules/@parcel/config-webextension/node_modules/@parcel/babel-ast-utils/lib/babelErrorUtils.js:14:18)
    at async Object.transform (/home/myuser/Projects/project/node_modules/@parcel/config-webextension/node_modules/@parcel/transformer-babel/lib/BabelTransformer.js:108:13)
    at async runTransformer (/home/myuser/Projects/project/node_modules/@parcel/core/lib/Transformation.js:651:3)
    at async Transformation.runPipeline (/home/myuser/Projects/project/node_modules/@parcel/core/lib/Transformation.js:422:36)
    at async Transformation.runPipelines (/home/myuser/Projects/project/node_modules/@parcel/core/lib/Transformation.js:363:40)
    at async Transformation.runPipelines (/home/myuser/Projects/project/node_modules/@parcel/core/lib/Transformation.js:386:34)
    at async Transformation.run (/home/myuser/Projects/project/node_modules/@parcel/core/lib/Transformation.js:277:19)
    at async Child.handleRequest (/home/myuser/Projects/project/node_modules/@parcel/workers/lib/child.js:255:9)
```

## 💁 Possible Solution

¯\\\_(ツ)\_/¯

## 🔦 Context

I'm attempting to create a Firefox extension using Preact and TypeScript

## 💻 Code Sample

index.html

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Extension</title>
    </head>
    <body>
        <div id="app"></div>
        <script src="./index.tsx"></script>
    </body>
</html>
```

index.tsx

```tsx
import { h, render } from 'preact';
import { App } from './App';

const root = document.getElementById('app');

if (!root) {
    throw new Error('No such element #app');
}

render(<App />, root);
```

App.tsx

```tsx
import { h } from 'preact';

export function App() {
    return <p>Hello from Preact!</p>;
}
```

manifest.json

```json
{
    "version": "0.0.1",
    "name": "Project Name",
    "manifest_version": 2
}
```

## 🌍 Your Environment

| Software         | Version(s)             |
| ---------------- | ---------------------- |
| Parcel           | 2.0.0-beta-1           |
| Node             | 15.8.0                 |
| npm/Yarn         | npm 7.5.1              |
| Operating System | Manjaro (Linux 5.10.7) |

**Comment by mischnic** [comment]
This should be fixed in the nightly version (`npm i parcel@nightly`). Can you verify that?

**Comment by RVxLab** [comment]
That didn't fix it, same error occurs. Also tried removing `.parcel-cache`, `node_modules` and `package-lock.json`.

**Comment by mischnic** [comment]
Have upgraded *all* parcel packages to the latest nightly?

```
        "@parcel/config-webextension": "^2.0.0-nightly.2151",
        "@parcel/transformer-typescript-tsc": "^2.0.0-alpha.3",
        "@parcel/validator-typescript": "^2.0.0-alpha.3",
        "parcel": "^2.0.0-beta.1",
```

**Comment by jaxry** [comment]
I was having the same, but updating all those packages to nightly fixed the issue. Thank you!

**Comment by RVxLab** [comment]
> Have you upgraded all parcel packages to the latest nightly?

I didn't, I actually didn't think of doing that. I'll try that when I get home and get back to you.

**Comment by RVxLab** [comment]
Updating all Parcel dependencies indeed fixed it. Sorry for the wasted time and thank you for the help!

**Comment by alpha-tango-kilo** [comment]
Hi all, I was experiencing this issue, I ran an `npm update` to bring everything to the latest and I now get a different error. Any pointers on what to do?

Error:
```
Error: config.setWatchGlob is not a function
TypeError: config.setWatchGlob is not a function
    at load (C:\...\project\\node_modules\@parcel\transformer-babel\lib\config.js:158:10)
    at async Object.loadConfig (C:\...\project\\node_modules\@parcel\transformer-babel\lib\BabelTransformer.js:66:5)
    at async ConfigLoader.loadPluginConfig (C:\...\project\\node_modules\@parcel\core\lib\ConfigLoader.js:204:9)
    at async PromiseQueue._runFn (C:\...\project\\node_modules\@parcel\utils\lib\PromiseQueue.js:108:7)
    at async PromiseQueue._next (C:\...\project\\node_modules\@parcel\utils\lib\PromiseQueue.js:95:5)
```

Relevant section from `package.json`:
```
"@parcel/config-webextension": "^2.0.0-nightly.2151",
"@parcel/transformer-typescript-tsc": "^2.0.0-alpha.3",
"parcel": "^2.0.0-nightly.598"
```

I'm also writing a Firefox extension in TypeScript. OS: Windows 10, Node: v14.15.4, `npm`: v6.14.10

**Comment by mischnic** [comment]
Make sure that all packages (including `@parcel/transformer-typescript-tsc`) are on the latest nightly

**Comment by alpha-tango-kilo** [comment]
As far as I'm aware, I am. `npm update` doesn't change anything and `npm outdated` shows nothing except the following:

```
Package            Current             Wanted  Latest  Location
parcel   2.0.0-nightly.598  2.0.0-nightly.598  1.12.4  project
```

**Comment by mischnic** [comment]
1. Remove all parcel related packages from package.json. Run `npm install`
1. Run `npm i -D @parcel/config-webextension@nightly @parcel/transformer-typescript-tsc@nightly parcel@nightly`

**Comment by alpha-tango-kilo** [comment]
That produced far weirder results than I was expecting. Thanks for your continued support on this, but I'm afraid I'm still getting an error, albeit a different one

```
Atk@SPICE-PC MINGW64 /d/Documents/Git Projects/_Uni_/Siphon (parcel-tsc)
$ npm run dev

> siphon@0.1.0 dev D:\Documents\Git Projects\_Uni_\Siphon
> parcel src/manifest.json --host localhost --target dev

ℹ Server running at http://localhost:1234
Installing @parcel/transformer-posthtml...
@parcel/package-manager: Added 12 packages via npm
⠋ Building siphon.svg...
TypeError: input.replace is not a function
    at markdownParser (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\markdown-ansi\lib\markdown-ansi.js:28:17)
    at prettyDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\utils\lib\prettyDiagnostic.js:77:171)
    at writeDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:233:45)
    at _report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:201:19)
    at Object.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:260:12)
    at ReporterRunner.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\ReporterRunner.js:140:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
TypeError: input.replace is not a function
    at markdownParser (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\markdown-ansi\lib\markdown-ansi.js:28:17)
    at prettyDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\utils\lib\prettyDiagnostic.js:77:171)
    at writeDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:233:45)
    at _report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:201:19)
    at Object.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:260:12)
    at ReporterRunner.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\ReporterRunner.js:140:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
TypeError: input.replace is not a function
    at markdownParser (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\markdown-ansi\lib\markdown-ansi.js:28:17)
    at prettyDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\utils\lib\prettyDiagnostic.js:77:171)
    at writeDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:233:45)
    at _report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:201:19)
    at Object.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:260:12)
    at ReporterRunner.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\ReporterRunner.js:140:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
TypeError: input.replace is not a function
    at markdownParser (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\markdown-ansi\lib\markdown-ansi.js:28:17)
    at prettyDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\utils\lib\prettyDiagnostic.js:77:171)
    at writeDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:233:45)
    at _report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:201:19)
    at Object.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:260:12)
    at ReporterRunner.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\ReporterRunner.js:140:31)
Installing @parcel/transformer-html...
@parcel/package-manager: Added 1 packages via npm
⠋ Building siphon.svg...
TypeError: input.replace is not a function
    at markdownParser (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\markdown-ansi\lib\markdown-ansi.js:28:17)
    at prettyDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\utils\lib\prettyDiagnostic.js:77:171)
    at writeDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:233:45)
    at _report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:201:19)
    at Object.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:260:12)
    at ReporterRunner.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\ReporterRunner.js:140:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
TypeError: input.replace is not a function
    at markdownParser (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\markdown-ansi\lib\markdown-ansi.js:28:17)
    at prettyDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\utils\lib\prettyDiagnostic.js:77:171)
    at writeDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:233:45)
    at _report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:201:19)
    at Object.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:260:12)
    at ReporterRunner.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\ReporterRunner.js:140:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
TypeError: input.replace is not a function
    at markdownParser (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\markdown-ansi\lib\markdown-ansi.js:28:17)
    at prettyDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\utils\lib\prettyDiagnostic.js:77:171)
    at writeDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:233:45)
    at _report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:201:19)
    at Object.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:260:12)
    at ReporterRunner.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\ReporterRunner.js:140:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
TypeError: input.replace is not a function
    at markdownParser (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\markdown-ansi\lib\markdown-ansi.js:28:17)
ℹ Server running at http://localhost:1234
× Build failed.
@parcel/transformer-js: Internal error: missing content
AssertionError [ERR_ASSERTION]: Internal error: missing content
    at UncommittedAsset.getCode (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\UncommittedAsset.js:218:27)
    at async Object.parse (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\transformer-js\lib\JSTransformer.js:220:16)
    at async Transformation.runTransformer (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\Transformation.js:655:17)
    at async Transformation.runPipeline (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\Transformation.js:427:36)
    at async Transformation.runPipelines (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\Transformation.js:368:40)
    at async Transformation.runPipelines (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\Transformation.js:391:34)
    at async Transformation.run (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\Transformation.js:280:19)
    at async Child.handleRequest (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\workers\lib\child.js:255:9)

Atk@SPICE-PC MINGW64 /d/Documents/Git Projects/_Uni_/Siphon (parcel-tsc)
$ npm run dev

> siphon@0.1.0 dev D:\Documents\Git Projects\_Uni_\Siphon
> parcel src/manifest.json --host localhost --target dev

ℹ Server running at http://localhost:1234
Installing @parcel/transformer-postcss...
@parcel/package-manager: Added 42 packages via npm
⠋ Building proxy.ts...
TypeError: input.replace is not a function
    at markdownParser (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\markdown-ansi\lib\markdown-ansi.js:28:17)
    at prettyDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\utils\lib\prettyDiagnostic.js:77:171)
    at writeDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:233:45)
    at _report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:201:19)
    at Object.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:260:12)
    at ReporterRunner.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\ReporterRunner.js:140:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
TypeError: input.replace is not a function
    at markdownParser (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\markdown-ansi\lib\markdown-ansi.js:28:17)
    at prettyDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\utils\lib\prettyDiagnostic.js:77:171)
    at writeDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:233:45)
    at _report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:201:19)
    at Object.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:260:12)
    at ReporterRunner.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\ReporterRunner.js:140:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
TypeError: input.replace is not a function
    at markdownParser (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\markdown-ansi\lib\markdown-ansi.js:28:17)
    at prettyDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\utils\lib\prettyDiagnostic.js:77:171)
    at writeDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:233:45)
    at _report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:201:19)
    at Object.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:260:12)
    at ReporterRunner.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\ReporterRunner.js:140:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
TypeError: input.replace is not a function
    at markdownParser (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\markdown-ansi\lib\markdown-ansi.js:28:17)
    at prettyDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\utils\lib\prettyDiagnostic.js:77:171)
    at writeDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:233:45)
    at _report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:201:19)
    at Object.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:260:12)
    at ReporterRunner.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\ReporterRunner.js:140:31)
Installing @parcel/transformer-css...
@parcel/package-manager: Added 2 packages via npm
⠋ Building proxy.ts...
TypeError: input.replace is not a function
    at markdownParser (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\markdown-ansi\lib\markdown-ansi.js:28:17)
    at prettyDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\utils\lib\prettyDiagnostic.js:77:171)
    at writeDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:233:45)
    at _report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:201:19)
    at Object.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:260:12)
    at ReporterRunner.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\ReporterRunner.js:140:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
TypeError: input.replace is not a function
    at markdownParser (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\markdown-ansi\lib\markdown-ansi.js:28:17)
    at prettyDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\utils\lib\prettyDiagnostic.js:77:171)
    at writeDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:233:45)
    at _report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:201:19)
    at Object.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:260:12)
    at ReporterRunner.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\ReporterRunner.js:140:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
TypeError: input.replace is not a function
    at markdownParser (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\markdown-ansi\lib\markdown-ansi.js:28:17)
    at prettyDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\utils\lib\prettyDiagnostic.js:77:171)
    at writeDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:233:45)
    at _report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:201:19)
    at Object.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:260:12)
    at ReporterRunner.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\ReporterRunner.js:140:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
TypeError: input.replace is not a function
    at markdownParser (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\markdown-ansi\lib\markdown-ansi.js:28:17)
    at prettyDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\utils\lib\prettyDiagnostic.js:77:171)
    at writeDiagnostic (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:233:45)
    at _report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:201:19)
    at Object.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:260:12)
    at ReporterRunner.report (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\ReporterRunner.js:140:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
TypeError: input.replace is not a function
    at markdownParser (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\markdown-ansi\lib\markdown-ansi.js:28:17)
ℹ Server running at http://localhost:1234
× Build failed.
@parcel/transformer-js: Internal error: missing content
AssertionError [ERR_ASSERTION]: Internal error: missing content
    at UncommittedAsset.getCode (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\UncommittedAsset.js:218:27)
    at async Object.parse (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\transformer-js\lib\JSTransformer.js:220:16)
    at async Transformation.runTransformer (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\Transformation.js:655:17)
    at async Transformation.runPipeline (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\Transformation.js:427:36)
    at async Transformation.runPipelines (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\Transformation.js:368:40)
    at async Transformation.runPipelines (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\Transformation.js:391:34)
    at async Transformation.run (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\Transformation.js:280:19)
    at async Child.handleRequest (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\workers\lib\child.js:255:9)

Atk@SPICE-PC MINGW64 /d/Documents/Git Projects/_Uni_/Siphon (parcel-tsc)
$ npm run dev

> siphon@0.1.0 dev D:\Documents\Git Projects\_Uni_\Siphon
> parcel src/manifest.json --host localhost --target dev

ℹ Server running at http://localhost:1234
× Build failed.
@parcel/transformer-js: Internal error: missing content
AssertionError [ERR_ASSERTION]: Internal error: missing content
    at UncommittedAsset.getCode (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\UncommittedAsset.js:218:27)
    at async Object.parse (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\transformer-js\lib\JSTransformer.js:220:16)
    at async Transformation.runTransformer (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\Transformation.js:655:17)
    at async Transformation.runPipeline (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\Transformation.js:427:36)
    at async Transformation.runPipelines (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\Transformation.js:368:40)
    at async Transformation.runPipelines (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\Transformation.js:391:34)
    at async Transformation.run (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\core\lib\Transformation.js:280:19)
    at async Child.handleRequest (D:\Documents\Git Projects\_Uni_\Siphon\node_modules\@parcel\workers\lib\child.js:255:9)
```

Subsequent runs of `npm run dev` kept pulling in more dependencies the project has never needed before, and ultimately still fails to run. Re-running the command only repeats the final error. Happy to provide any further information needed

**Comment by mischnic** [comment]
Looks like https://github.com/parcel-bundler/parcel/issues/5829
