### ISSUE TITLE
parcelRequire is not a function (Nightly 577)

### ISSUE THREAD

**Issue by ittaibaratz** [parcel-bundler/parcel#5814]
# 🐛 bug report

After a successful build of our monorepo, opening the web app shows the following error (With minification disabled):

```
Uncaught TypeError: parcelRequire is not a function
```

Looking at the JS source, this happens because parcelRequire is called before it is defined:
```
  var $parcel$global = typeof globalThis !== 'undefined' ? globalThis : typeof self !== 'undefined' ? self : typeof window !== 'undefined' ? window : typeof global !== 'undefined' ? global : {};
  var parcelRequire = $parcel$global.parcelRequired28b;
  var $f2593f70eaebde174314e6f9aabfc2a0$init = parcelRequire("7niVC");
   ...
  var $bf482cc9ddc9dcdfc826e2d46e1a9602$init = parcelRequire("5OWw9");
  var parcelRequireName = "parcelRequired28b";
  var $parcel$modules = {};
  var $parcel$bundles = {};
  if (parcelRequire == null)
```

Since the last `if` generates the parcelRequire function, calling at ahead of that statement fails.

## 🎛 Configuration (.babelrc, package.json, cli command)

Babel:
```
module.exports = function (api) {
  api.cache(true);

  return {
    presets: [
      [
        '@babel/preset-env',
        {
          bugfixes: true,
          corejs: 2,
          useBuiltIns: 'entry'
        }
      ],
      '@babel/preset-react',
      '@babel/preset-typescript'
    ],
    plugins: [
      '@babel/plugin-proposal-class-properties',
      ["@babel/plugin-proposal-decorators", {decoratorsBeforeExport: true}]
    ]
  }
};
```

Our entry is index.html which has a few JS resources:
```
    <script src="./polyfills.js"></script>
    <script src="./react.js"></script>
    <!-- Placeholder for insertion of shell js bundle -->
    <script src="./main.js"></script>
    <script defer src="./browser-support.js"></script>
    <script defer src="./error-page.js"></script>
```

polyfills includes core-js polyfills as well as some initilization code and runs fine.
react includes React/ReactDOM and runs fine.
main.js is where our App component lives, and is where the problem above happens.
 
## 🤔 Expected Behavior

Bundled app should load correctly.

## 😯 Current Behavior

Bundled app does not load correctly.

Note that when running a dev server, it does run fine - The problem is only with the build.

## 💻 Code Sample

I can provide access to @devongovett (Same company). Can also try to do a minimal reproduction if required.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0 nightly 577 |
| Node             | 14/15 (latest) |
| npm/Yarn         | latest | 
| Operating System | CentOS / Mac OS |

**Comment by devongovett** [comment]
My guess is it's related to imports between entries (e.g. main.js importing from react.js). This appears to be quite broken at the moment. [Minimal reproduction](https://parcel2-repl.now.sh/#JTdCJTIyY3VycmVudFByZXNldCUyMiUzQSUyMkJhc2ljJTIwUGFnZSUyMiUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJtaW5pZnklMjIlM0FmYWxzZSUyQyUyMnNjb3BlSG9pc3QlMjIlM0F0cnVlJTJDJTIyc291cmNlTWFwcyUyMiUzQWZhbHNlJTJDJTIycHVibGljVXJsJTIyJTNBJTIyJTJGX19yZXBsX2Rpc3QlMjIlMkMlMjJ0YXJnZXRUeXBlJTIyJTNBJTIyYnJvd3NlcnMlMjIlMkMlMjJ0YXJnZXRFbnYlMjIlM0FudWxsJTJDJTIyb3V0cHV0Rm9ybWF0JTIyJTNBbnVsbCUyQyUyMmhtciUyMiUzQWZhbHNlJTJDJTIybW9kZSUyMiUzQSUyMnByb2R1Y3Rpb24lMjIlMkMlMjJyZW5kZXJHcmFwaHMlMjIlM0FmYWxzZSUyQyUyMnZpZXdTb3VyY2VtYXBzJTIyJTNBZmFsc2UlMkMlMjJkZXBlbmRlbmNpZXMlMjIlM0ElNUIlNUQlN0QlMkMlMjJhc3NldHMlMjIlM0ElNUIlNUIlMjJzcmMlMkZpbmRleC5odG1sJTIyJTJDJTIyJTNDc2NyaXB0JTIwc3JjJTNEJTVDJTIyLiUyRmEuanMlNUMlMjIlM0UlM0MlMkZzY3JpcHQlM0UlNUNuJTNDc2NyaXB0JTIwc3JjJTNEJTVDJTIyLiUyRmIuanMlNUMlMjIlM0UlM0MlMkZzY3JpcHQlM0UlMjIlMkMxJTVEJTJDJTVCJTIyc3JjJTJGYS5qcyUyMiUyQyUyMmV4cG9ydCUyMGZ1bmN0aW9uJTIwYSgpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMDIlM0IlNUNuJTdEJTIyJTVEJTJDJTVCJTIyc3JjJTJGYi5qcyUyMiUyQyUyMmltcG9ydCUyMCU3QmElN0QlMjBmcm9tJTIwJy4lMkZhJyUzQiU1Q25jb25zb2xlLmxvZyhhKCklMkMlMjBpbXBvcnQoJy4lMkZjJykudGhlbigoJTdCYyU3RCklMjAlM0QlM0UlMjBjKCkpKSUzQiUyMiU1RCUyQyU1QiUyMnNyYyUyRmMuanMlMjIlMkMlMjIlMjIlNUQlNUQlN0Q=)

It's also even more broken without the dynamic import, in which case `parcelRequire` is not defined at all. [Reproduction](https://parcel2-repl.now.sh/#JTdCJTIyY3VycmVudFByZXNldCUyMiUzQSUyMkJhc2ljJTIwUGFnZSUyMiUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJtaW5pZnklMjIlM0FmYWxzZSUyQyUyMnNjb3BlSG9pc3QlMjIlM0F0cnVlJTJDJTIyc291cmNlTWFwcyUyMiUzQWZhbHNlJTJDJTIycHVibGljVXJsJTIyJTNBJTIyJTJGX19yZXBsX2Rpc3QlMjIlMkMlMjJ0YXJnZXRUeXBlJTIyJTNBJTIyYnJvd3NlcnMlMjIlMkMlMjJ0YXJnZXRFbnYlMjIlM0FudWxsJTJDJTIyb3V0cHV0Rm9ybWF0JTIyJTNBbnVsbCUyQyUyMmhtciUyMiUzQWZhbHNlJTJDJTIybW9kZSUyMiUzQSUyMnByb2R1Y3Rpb24lMjIlMkMlMjJyZW5kZXJHcmFwaHMlMjIlM0FmYWxzZSUyQyUyMnZpZXdTb3VyY2VtYXBzJTIyJTNBZmFsc2UlMkMlMjJkZXBlbmRlbmNpZXMlMjIlM0ElNUIlNUQlN0QlMkMlMjJhc3NldHMlMjIlM0ElNUIlNUIlMjJzcmMlMkZpbmRleC5odG1sJTIyJTJDJTIyJTNDc2NyaXB0JTIwc3JjJTNEJTVDJTIyLiUyRmEuanMlNUMlMjIlM0UlM0MlMkZzY3JpcHQlM0UlNUNuJTNDc2NyaXB0JTIwc3JjJTNEJTVDJTIyLiUyRmIuanMlNUMlMjIlM0UlM0MlMkZzY3JpcHQlM0UlMjIlMkMxJTVEJTJDJTVCJTIyc3JjJTJGYS5qcyUyMiUyQyUyMmV4cG9ydCUyMGZ1bmN0aW9uJTIwYSgpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMDIlM0IlNUNuJTdEJTIyJTVEJTJDJTVCJTIyc3JjJTJGYi5qcyUyMiUyQyUyMmltcG9ydCUyMCU3QmElN0QlMjBmcm9tJTIwJy4lMkZhJyUzQiU1Q25jb25zb2xlLmxvZyhhKCkpJTNCJTIyJTVEJTVEJTdE)

**Comment by devongovett** [comment]
Looks like the first issue (prelude ordering) was fixed by #5184. The second issue (not including the prelude at all) should be fixed by #5839.

**Comment by oudbd** [comment]
The "parcelRequire is not a function" issue still exists in Nightly 610

**Comment by Andrew-Dyachenko** [comment]
I got the same problem in **parcel: 2.0.0-beta.2**
`Uncaught TypeError: e.parcelRequire5a76 is not a function`
