### ISSUE TITLE
Inline code generation creates broken reference

### ISSUE THREAD

**Issue by koblas** [parcel-bundler/parcel#6015]
# 🐛 bug report

Generated code is in error.   The following line from `node_modules/aws-sdk/lib/node_library.js` which is

```js
util.Buffer = require('buffer').Buffer;
```

generates the wrong runtime code with inline modules.

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
  "name": "bug",
  "main": "build/index.js",
  "source": "src/main.ts",
  "scripts": {
    "build": "parcel build src/main.ts --target main --no-optimize"
  },
  "targets": {
    "main": {
      "context": "node",
      "isLibrary": true,
      "outputFormat": "commonjs",
      "includeNodeModules": {
        "chrome-aws-lambda": false,
        "puppeteer-core": false
      },
      "sourceMap": false,
      "engines": {
        "node": ">=12.0.0"
      }
    }
  },
  "engines": {
    "node": ">=12.0.0"
  },

  "version": "1.0.0",
  "description": "",
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "aws-sdk": "^2.866.0"
  },
  "devDependencies": {
    "parcel": "^2.0.0-beta.2"
  }
}
```

## 🤔 Expected Behavior

```sh
$ fgrep '$init().Buffer = ' build/index.js
$63f44eb3ff226eac7da1f54226a0e697$init().Buffer = Buffer;
```

## 😯 Current Behavior

```sh
$ fgrep '$init().Buffer = ' build/index.js
$63f44eb3ff226eac7da1f54226a0e697$init().Buffer = {};

```

## 🔦 Context

Unable to create a production ready build due to bad code generation.

## 💻 Code Sample

main.ts for review -- more to trigger the bug.

```ts
import * as AWS from 'aws-sdk';

export async function handle() {

  const payload = { test: true }
  const bucket = "some-test-bucket"
  const key = "xyzzy"

          const s3 = new AWS.S3(new AWS.Config({}));
        await s3
          .putObject({
            Body: Buffer.from(JSON.stringify(payload)),
            Bucket: bucket,
            Key: key,
          })
          .promise();
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0.beta-2
| Node             | node 12
| npm/Yarn         | nom
| Operating System |

**Comment by devongovett** [comment]
Possibly fixed in beta.3.1?

**Comment by mischnic** [comment]
This specific case seems fixed, but aws-sdk still doesn't work: https://github.com/parcel-bundler/parcel/issues/6519
