### ISSUE TITLE
Cannot resolve dependency './../../../../../../../../../..' at '/'

### ISSUE THREAD

**Issue by daggerok** [parcel-bundler/parcel#602]
.babelrc
```json
{
  "presets": [
    "env",
    "stage-0"
  ]
}
```
package.json
```json
"devDependencies": {
  "babel-preset-env": "1.6.1",
  "babel-preset-stage-0": "6.24.1",
  "parcel-bundler": "1.4.1"
},
"scripts": {
  "start": "parcel -p 3000 ./app/index.html"
}
```
failed when app/index.html contains non # hrefs, like
```html
<nav>
  <div class="grid-header nav-wrapper blue-grey lighten-1">
    <a href="/" class="brand-logo">&nbsp; Knockout.js</a>
    <a href="/" data-activates="mobile-menu" class="button-collapse">
      <i class="material-icons">menu</i>
    </a>
    <ul class="right hide-on-med-and-down">
      <li><a href="/">Home</a></li>
      <li><a href="/link1">Link 1</a></li>
      <li><a href="/link2">Link 2</a></li>
    </ul>
    <ul class="side-nav" id="mobile-menu">
      <li><a href="/">Home</a></li>
      <li><a href="/link1">Login</a></li>
      <li><a href="/link2">Logout</a></li>
    </ul>
  </div>
</nav>
```
error if index.html page contains `<a href="/" ...>...</a>`:
```bash
yarn start
yarn run v1.3.2
$ parcel -p 3000 ./app/index.html
Server running at http://localhost:3000 
🚨  /Users/mak/Documents/code/test/js/knockout/knockout-examples/computed/app/index.html: Cannot resolve dependency './../../../../../../../../../..' at '/'
    at /Users/mak/Documents/code/test/js/knockout/knockout-examples/computed/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/Users/mak/Documents/code/test/js/knockout/knockout-examples/computed/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/mak/Documents/code/test/js/knockout/knockout-examples/computed/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/mak/Documents/code/test/js/knockout/knockout-examples/computed/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:166:21)
```
other info
```bash
yarn -v
1.3.2

node -v
v9.4.0

npm -v
5.6.0

uname -a
Darwin kostromin-mb.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
```

note: build works fine if replace all `href="/.."` to `href="#/..."`

---
Regards,
Maksim

**Comment by underscoredotspace** [comment]
Further to your note, I've noticed it still fails with `href="/#/..."`

**Comment by daggerok** [comment]
@underscoredotspace check this one https://github.com/daggerok/knockout-examples/tree/master/computed

for me it's built with no errors

```bash
$ parcel build ./app/index.html --no-cache --out-dir='./dist' --public-url='/'
⏳  Building materialize.css...
⏳  Building Roboto-Bold.woff...
Dropping unreachable code [0:9815,1]
⏳  Building browser.js...
Dropping duplicated definition of variable o [0:204,12]
Dropping duplicated definition of variable e [0:522,20]
Boolean && always false [0:600,12]
Boolean && always false [0:601,103]
Boolean && always false [0:656,649]
Boolean && always false [0:660,160]
Boolean && always false [0:698,133]
Boolean && always false [0:699,21]
Dropping duplicated definition of variable E [0:664,16]
Dropping duplicated definition of variable j [0:748,20]
Dropping unused variable count [0:2307,12]
Side effects in initialization of unused variable windowWidth [0:2439,12]
Side effects in initialization of unused variable windowHeight [0:2440,12]
Dropping unused variable originalWidth [0:2266,10]
Dropping unused variable originalHeight [0:2267,10]
Side effects in initialization of unused variable activeRect [0:2740,14]
Dropping unused variable timeout [0:2811,8]
Dropping unreachable code [0:3052,2]
Declarations in unreachable code! [0:3052,2]
Side effects in initialization of unused variable width [0:3162,10]
Side effects in initialization of unused variable direction [0:3872,18]
Side effects in initialization of unused variable velocityX [0:3875,18]
Dropping unused variable unique_id [0:4133,6]
Dropping unused variable left [0:4621,10]
Dropping unused variable left [0:4555,8]
Dropping unused variable chips [0:5514,10]
Dropping unused variable time [0:5943,8]
Dropping unreachable code [0:7120,2]
Declarations in unreachable code! [0:7120,2]
Dropping unreachable code [0:7009,4]
Declarations in unreachable code! [0:7009,4]
Dropping unreachable code [0:8451,51]
Declarations in unreachable code! [0:8451,51]
Side effects in initialization of unused variable offset [0:8907,8]
Side effects in initialization of unused variable width [0:8908,8]
Side effects in initialization of unused variable height [0:8909,8]
Side effects in initialization of unused variable align [0:8910,8]
Dropping unused variable self [0:8911,8]
Dropping unused variable xTranslation [0:9463,57]
Side effects in initialization of unused variable imageHeight [0:9744,16]
Dropping unused variable isCenterY [0:9949,14]
⏳  Building jquery.js...
Dropping duplicated definition of variable p [0:8,362]
Dropping duplicated definition of variable f [0:22,160]
Dropping duplicated definition of variable e [0:26,287]
Dropping duplicated definition of variable k [0:29,252]
Dropping duplicated definition of variable f [0:30,437]
Dropping duplicated definition of variable l [0:47,162]
Dropping duplicated definition of variable g [0:47,196]
Dropping duplicated definition of variable G [0:47,204]
Dropping duplicated definition of variable d [0:67,360]
Dropping duplicated definition of variable d [0:67,494]
Dropping duplicated definition of variable f [0:83,254]
Dropping duplicated definition of variable f [0:83,359]
Dropping duplicated definition of variable f [0:103,393]
Dropping duplicated definition of variable g [0:113,408]
Dropping duplicated definition of variable p [0:120,41]
Dropping duplicated definition of variable C [0:120,469]
Dropping duplicated definition of variable r [0:120,473]
Dropping unreachable code [0:9815,1]
✨  Built in 8.16s.
✨  Done in 9.85s.
```

---
Regards,

**Comment by daggerok** [comment]
@underscoredotspace yes, but I told that it not fails of starts with hash, but `href="/#/..."` starts form '/', not '#'

**Comment by ayarin0x0** [comment]
✨ It seems like parcel (1.5.0) has fixed this, here it is:

> Virtualpaths, throw file not found error Details #487.

<br />
<br />

🚨 Here is what i think, maybe not correct.
In parcel (1.4.1), HTMLAsset may mistake virtual path for a dependency,

https://github.com/parcel-bundler/parcel/blob/68258b1e53d086f173d2888d9fa367fcba891807/src/assets/HTMLAsset.js#L42-L54

but in fact, this 'dependency' is not 'illegal',
then it `console.error('Cannot resolve dependency')`

So, if add this:

```js
if (node.attrs) {
    for (let attr in node.attrs) {
      let elements = ATTRS[attr];
      if (elements && elements.includes(node.tag)) {
        let assetPath = this.addURLDependency(node.attrs[attr]);

        /* patch */
        if (node.tag === 'a' && node.attrs[attr].startsWith('/')) {
            continue
        }

        if (!isURL(assetPath)) {
          assetPath = urlJoin(this.options.publicURL, assetPath);
        }
        node.attrs[attr] = assetPath;
        this.isAstDirty = true;
      }
    }
}
```

`a[href='/']` can temporary work fine.

Example:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>#602</title>
</head>
<body>
    <div id="app">
        <a href="/"></a>
        <a href="/home"></a>
        <a href="/sidebar/foo"></a>
        <a href="assets/harusame.jpg" style="display: block; width: 100px; height: 100px; background-color: rgba(9, 19, 39, .5)">Link to asset</a>
    </div>
</body>
</html>
```

Before:

```shell
$ parcel irodorin.html
Server running at http://localhost:1234
⏳  Building...

Resolver line 17: resolved[0] E:\irodorin\irodorin\irodorin.html
⏳  Building irodorin.html...
Resolver line 17: resolved[0] E:\irodorin\irodorin\assets\harusame.jpg
⏳  Building harusame.jpg...
🚨  E:\irodorin\irodorin\irodorin.html: Cannot resolve dependency './..\..' at 'E:\'

...
...
```

After:

```shell
$ rm -rf .cache dist

$ parcel irodorin.html
Server running at http://localhost:1234
⏳  Building...

Resolver line 17: resolved[0] E:\irodorin\irodorin\irodorin.html
⏳  Building irodorin.html...
Resolver line 17: resolved[0] E:\irodorin\irodorin\assets\harusame.jpg
⏳  Building harusame.jpg...
✨  Built in 297ms.

```

![in-browser](https://user-images.githubusercontent.com/12593358/35559116-393c4dce-05ed-11e8-83fe-e37529a18f34.png)

As for `a[href='#']`, `isUrl` has filtered it:

https://github.com/parcel-bundler/parcel/blob/68258b1e53d086f173d2888d9fa367fcba891807/src/assets/HTMLAsset.js#L47-L49

https://github.com/parcel-bundler/parcel/blob/68258b1e53d086f173d2888d9fa367fcba891807/src/utils/is-url.js#L3-L4

https://github.com/parcel-bundler/parcel/blob/68258b1e53d086f173d2888d9fa367fcba891807/src/utils/is-url.js#L8-L11

**Comment by davidnagli** [comment]
So is this completely fixed in the latest version?

**Comment by marcuslindfeldt** [comment]
I still have this issue in 1.5.1. The bundler probably shouldn't fail but rather give a warning and don't process the url or something. I just want to create a relative link to a resource hosted on the same domain but in another service via an nginx reverse proxy. E.g.
```
<a href="/otherservice/example.html">...</a>
```

**Comment by daggerok** [comment]
Hello again,

I can confirm that 1.5.1 fixed my issue.

Thank you!

---
Regards,
Maksim
