### ISSUE TITLE
Service Workers and React HMR do not work well together

### ISSUE THREAD

**Issue by rabelloo** [parcel-bundler/parcel#6129]
# 🐛 bug report

When serving a React application with a service worker created by [msw](https://github.com/mswjs/msw) with Parcel 2, if HRM is enabled it fails with the following error:

![image](https://user-images.githubusercontent.com/18623773/114760802-a2901800-9d57-11eb-834e-cdf4055d2e81.png)

If `--no-hmr` is used it serves fine, as long as the path is wrapped using the `url:` named pipeline.

## 🎛 Configuration (.babelrc, package.json, cli command)

Simply serving with `parcel src/index.html`

`msw` worker registered with:
```tsx
const url = require('url:../dist/mockServiceWorker.js');
const { worker } = await import('./mocks/browser');
await worker.start({ serviceWorker: { url } });
```

This does not work:
`const url = new URL('../dist/mockServiceWorker.js', import.meta.url)`

## 🤔 Expected Behavior

HMR should work along with msw and other service workers.

## 😯 Current Behavior

`--no-hmr` serves fine. Not setting the option produces the error in the image above.

## 💁 Possible Solution

I suppose if the service worker wasn't wrapped in Parcel's scope hoisting it would have access to window?

To be honest, I wouldn't mind being able to directly access that file in dev-server without having to process its path like we could in Parcel 1.

## 🔦 Context

The goal is to use `msw` and React HMR in Parcel 2.

## 💻 Code Sample

https://github.com/rabelloo/parcel-msw

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.2   |
| Node             | 15.12.0   |
| npm         | 7.7.5  |
| Operating System | MacOS

**Comment by devongovett** [comment]
I think this should be fixed in the latest nightlies if not the last beta. Workers are now skipped when inserting the react refresh runtime.

**Comment by Poky85** [comment]
@devongovett  I updated service worker code sample to use Parcel 2.3.1 and issue is still there

https://github.com/Poky85/parcel-msw

![image](https://user-images.githubusercontent.com/1475938/154146644-b793680b-038c-41b9-a584-3cb7fd49a75b.png)

Is there way to reference service worker using import?

Using `new URL('service-worker.js', import.meta.url)` approach requires Typescript to be configured to generate ESM which is not possible in my project setup.

Thank you
