### ISSUE TITLE
🐛 `parcel watch` in 1.5.0 stuck on "Building someFile.js..."

### ISSUE THREAD

**Issue by mBeierl** [parcel-bundler/parcel#637]
I tried updating my project from parcel-bundler 1.4.1 to 1.5.0, but `parcel watch` doesn't finish. I removed the cache folder manually and started the watch command (see exact CLI command below). It gets stuck at some random file, displaying `∞  Building someFile.js...` forever.

The `parcel build` command works btw.

### 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc:
```js
{
  "presets": ["env", "es2015", "react"],
  "plugins": [
    "transform-class-properties",
    "transform-object-rest-spread",
    "transform-decorators-legacy",
    "transform-es3-member-expression-literals",
    "transform-es3-property-literals"
  ],
  "env": {
    "production": {
      "plugins": ["transform-remove-debugger", "transform-remove-console"]
    }
  }
}
```

package.json (without name etc. but all deps & scripts):
```js
{
  "dependencies": {
    "animate.css": "^3.5.2",
    "babel-polyfill": "^6.26.0",
    "flag-icon-css": "^2.8.0",
    "immer": "^0.3.0",
    "lodash": "^4.17.4",
    "material-ui": "^1.0.0-beta.12",
    "material-ui-icons": "^1.0.0-beta.10",
    "object.values": "^1.0.4",
    "pubsub-js": "^1.5.7",
    "rc-collapse": "^1.7.6",
    "react": "16.2.0",
    "react-dom": "16.2.0",
    "react-json-view": "^1.13.0",
    "react-onclickoutside": "^6.4.0",
    "react-redux": "5.0.6",
    "react-treebeard": "^2.0.3",
    "redux": "3.7.2",
    "redux-saga": "^0.15.6",
    "redux-thunk": "^2.2.0",
    "reselect": "^3.0.1",
    "workerize": "^0.1.2"
  },
  "devDependencies": {
    "babel-eslint": "7.2.3",
    "babel-jest": "^22.0.3",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-es3-member-expression-literals": "^6.22.0",
    "babel-plugin-transform-es3-property-literals": "^6.22.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-plugin-transform-remove-console": "^6.8.5",
    "babel-plugin-transform-remove-debugger": "^6.8.5",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "cross-env": "^5.0.2",
    "enzyme": "^2.8.2",
    "eslint": "4.1.1",
    "eslint-config-react-app": "^2.0.1",
    "eslint-plugin-flowtype": "2.34.1",
    "eslint-plugin-import": "2.6.0",
    "eslint-plugin-jsx-a11y": "5.1.1",
    "eslint-plugin-react": "^7.5.1",
    "husky": "^0.14.3",
    "identity-obj-proxy": "^3.0.0",
    "jest": "22.1.2",
    "jest-css-modules": "^1.1.0",
    "lint-staged": "^6.0.0",
    "node-sass": "^4.5.3",
    "parcel-bundler": "1.5.0",
    "prettier": "1.10.2",
    "react-test-renderer": "^16.2.0",
    "redux-mock-store": "^1.2.3",
    "sinon": "^4.1.6"
  },
  "scripts": {
    "watch": "cross-env REACT_APP_VERSION=$npm_package_version parcel watch src/index.js --out-dir ./public/static --public-url ./static/",
    "test": "jest",
    "lint": "eslint ./src",
    "pretty": "prettier --write \"src/**/*.{js,css,md,scss}\"",
    "precommit": "lint-staged",
    "prepush": "npm run test --coverage"
  },
  "lint-staged": {
    "src/**/*.{js,css,md,scss}": [
      "prettier --write",
      "git add"
    ],
    "src/**/*.js": "eslint --max-warnings=0"
  },
  "jest": {
    "rootDir": "src",
    "moduleNameMapper": {
      "\\.(css|less|scss)$": "identity-obj-proxy"
    },
    "transform": {
      "^.+\\.js$": "babel-jest",
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/fileTransformer.js"
    },
    "setupFiles": [
      "<rootDir>/setupTests.js"
    ]
  }
}
```

Used cli command: `yarn watch` (see script in package.json above)

### 🤔 Expected Behavior

I expect the parcel watch command to finish building.

### 😯 Current Behavior

The command is getting stuck while building.

### 💁 Possible Solution

No idea, sorry.

### 🔦 Context

I will have to stay at version 1.4.1 until the watch command works again in my project, as I heavily depend on the watch command during development.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.5.0 |
| Node             | 8.9.3 |
| npm         | 5.6.0 |
| yarn         | 1.3.2 |
| Operating System | Microsoft Windows 10 Enterprise [Version 10.0.15063] |

**Comment by DeMoorJasper** [comment]
Is there anyway you could provide us with the project where this accured or a project where we could reproduce this?

**Comment by mBeierl** [comment]
I sadly can't share the project I'm experiencing the issue in, but I stripped a copy down to re-create the build config and structure and the issue is reproducible in that stripped down project.

You can find the repo here: https://github.com/mBeierl/parcel-watch-issue

**Comment by DeMoorJasper** [comment]
I tried your repository and found out, that if we change the workerfarmOptions to this, it works:
```
let opts = {
  maxConcurrentWorkers: getNumWorkers(),
  maxCallTime: 1000,
  maxConcurrentCallsPerWorker: 2,
  maxRetries: 2
};
```
this let's a call to the remote worker time out after 1second, and retries 2 times after a timeout and apparently it doesn't throw a workerTimeout error or any other error, so something inside the code or worker-farm code is freezing the individual workers.

**Comment by mBeierl** [comment]
Hmm interesting. I will try to set-up a local development of parcel and debug a little myself. I haven't looked into parcel's source before, so it might take while.

**Comment by niicojs** [comment]
I'm having the same issue at each update.  
I usually get into this to solve it: 
- update parcel
- remove .cache
- remove build folder
- re-update parcel

and it ends up working...
I never looked closer as I'm doing other stuff when it fails :)

**Comment by mikkiek** [comment]
I'm having the same issue with niicojs on Windows. his solution with update parcel helps me... once per run.

**Comment by Slapbox** [comment]
Alas, I have to do this all every startup of Parcel or it fails to finish building about 75% of the time.

**Comment by jkrehm** [comment]
I'm running into this same issue on my Windows 10 machine. @DeMoorJasper's change to the work options has made it work consistently for me. Specifically the `maxCallTime` setting (I removed `maxConcurrentCallsPerWorker` and it's still working).

Like others, mine seems to get bogged down in the babel-polyfills.

**Comment by mBeierl** [comment]
I can confirm that adding `maxCallTime = 1000` to the options before initiating the local worker inside the WorkerFarm class fixes the issue consistently for me.

**Comment by amykapernick** [comment]
I'm having the same issue, but can't for the life of me find anything about workerFarmOptions. Any assistance?
```
	"dependencies": {
		"node-sass": "^4.7.2",
		"npm": "^5.7.1",
		"react": "^16.2.0",
		"react-dom": "^16.2.0",
		"react-feather": "^1.0.8",
		"react-helmet": "^5.2.0",
		"react-icons": "^2.2.7",
		"react-media": "^1.6.1",
		"react-router-dom": "^4.2.2",
		"react-svg": "^2.2.10"
	},
	"devDependencies": {
		"autoprefixer": "^7.2.5",
		"babel-eslint": "^8.2.1",
		"babel-preset-env": "^1.6.1",
		"babel-preset-react": "^6.24.1",
		"eslint": "^4.17.0",
		"eslint-config-airbnb": "^16.1.0",
		"eslint-plugin-import": "^2.8.0",
		"eslint-plugin-jsx-a11y": "^6.0.3",
		"eslint-plugin-react": "^7.6.1",
		"parcel-bundler": "^1.6.2"
	}
```

**Comment by DeMoorJasper** [comment]
@amykapernick the sometimes scss sometimes js is probably due to the multiple workers it’s highly likely that it’s always the same file

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by amykapernick** [comment]
@DeMoorJasper the files are always different (footer, header etc) so it's likely to be app.js or index.js then.

Any suggestions on resolving this? It's not actually giving an error, just getting stuck and freezing my terminal

I just got a new computer and I need to get this working because I have a bunch of updates to do. I've tried clearing and updating things multiple times but no success

**Comment by jeanfortheweb** [comment]
Actually fixed in #901 already a while ago, but not yet merged. Probably just upvote the PR then it should get into the next patch I guess :)

@amykapernick Yes, it's always random, but it's not call time related but call count.

**Comment by pke** [comment]
This bug is still in 1.6.2 and it happens on random files not always the same. Clearing the cache does not help.

**Comment by hugufc** [comment]
Still in 1.7.0.

**Comment by damey2011** [comment]
Still in 1.7.0.. It's frustrating

**Comment by dspacejs** [comment]
Yep, still have it in 1.8.1. I'm on Ubuntu 18.04, not Windows

**Comment by DeMoorJasper** [comment]
This is probably a different issue @dspacejs see #1331
