### ISSUE TITLE
Parcel 2 Tries to Redefine Non-Configurable Property

### ISSUE THREAD

**Issue by brettkolodny** [parcel-bundler/parcel#6661]
# 🐛 bug report

Parcel v1 is able to bundle and serve the `@polkadot/api` library successfully but Parcel v2 throws an error in the browser.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "context": "browser",
  "devDependencies": {
    "parcel": "^2.0.0-beta.3.1"
  },
  "dependencies": {
    "@polkadot/api": "^5.2.1"
  }
}
```

## 🤔 Expected Behavior

Parcel should bundle and serve the package correctly.

## 😯 Current Behavior

Throws an error in the browser: `Uncaught TypeError: can't redefine non-configurable property "packageInfo"`

## 💻 Code Sample

https://github.com/brettkolodny/polkadot-parcelv2-test

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^2.0.0-beta.3.1
| Node             | v14.17.0
| npm/Yarn         | 1.22.10
| Operating System | Pop_OS!

**Comment by devongovett** [comment]
Could you try a nightly version of parcel to see if this is already fixed?

**Comment by brettkolodny** [comment]
> Could you try a nightly version of parcel to see if this is already fixed?

Issue still persists after upgrading to `"parcel": "^2.0.0-nightly.792"`
