### ISSUE TITLE
Segmentation fault in alpine Docker on M1 Mac

### ISSUE THREAD

**Issue by sethsamuel** [parcel-bundler/parcel#7402]
# 🐛 bug report

Running parcel in an alpine Docker container on an M1 Mac results in a Segmentation Fault.

## 🎛 Configuration (.babelrc, package.json, cli command)

```
FROM node:alpine

RUN apk add --no-cache build-base python3 && \
    apk add --no-cache gcc g++

RUN npm i -g parcel

CMD parcel
```

## 🤔 Expected Behavior

Parcel should run without crashing.

## 😯 Current Behavior

Parcel segfaults.

Running gdb:

```
#0  0x0000000000005ed0 in ?? ()
#1  0x0000ffff85c613f0 in mdb_env_open () from /usr/local/lib/node_modules/parcel/node_modules/lmdb-store/prebuilds/linux-arm64/node.abi102.node
#2  0x0000ffff85c613f0 in mdb_env_open () from /usr/local/lib/node_modules/parcel/node_modules/lmdb-store/prebuilds/linux-arm64/node.abi102.node
#3  0x0000ffff85c613f0 in mdb_env_open () from /usr/local/lib/node_modules/parcel/node_modules/lmdb-store/prebuilds/linux-arm64/node.abi102.node
#4  0x0000ffff85c613f0 in mdb_env_open () from /usr/local/lib/node_modules/parcel/node_modules/lmdb-store/prebuilds/linux-arm64/node.abi102.node
#5  0x0000ffff85c613f0 in mdb_env_open () from /usr/local/lib/node_modules/parcel/node_modules/lmdb-store/prebuilds/linux-arm64/node.abi102.node
#6  0x0000ffff85c613f0 in mdb_env_open () from /usr/local/lib/node_modules/parcel/node_modules/lmdb-store/prebuilds/linux-arm64/node.abi102.node
#7  0x0000ffff85c613f0 in mdb_env_open () from /usr/local/lib/node_modules/parcel/node_modules/lmdb-store/prebuilds/linux-arm64/node.abi102.node
#8  0x0000ffff85c613f0 in mdb_env_open () from /usr/local/lib/node_modules/parcel/node_modules/lmdb-store/prebuilds/linux-arm64/node.abi102.node
#9  0x0000ffff85c613f0 in mdb_env_open () from /usr/local/lib/node_modules/parcel/node_modules/lmdb-store/prebuilds/linux-arm64/node.abi102.node
#10 0x0000ffff85c613f0 in mdb_env_open () from /usr/local/lib/node_modules/parcel/node_modules/lmdb-store/prebuilds/linux-arm64/node.abi102.node
#11 0x0000ffff85c613f0 in mdb_env_open () from /usr/local/lib/node_modules/parcel/node_modules/lmdb-store/prebuilds/linux-arm64/node.abi102.node
#12 0x0000ffff85c613f0 in mdb_env_open () from /usr/local/lib/node_modules/parcel/node_modules/lmdb-store/prebuilds/linux-arm64/node.abi102.node
#13 0x0000ffff85c613f0 in mdb_env_open () from /usr/local/lib/node_modules/parcel/node_modules/lmdb-store/prebuilds/linux-arm64/node.abi102.node
#14 0x0000ffff85c613f0 in mdb_env_open () from /usr/local/lib/node_modules/parcel/node_modules/lmdb-store/prebuilds/linux-arm64/node.abi102.node
#15 0x0000ffff85c613f0 in mdb_env_open () from /usr/local/lib/node_modules/parcel/node_modules/lmdb-store/prebuilds/linux-arm64/node.abi102.node
#16 0x0000ffff85c613f0 in mdb_env_open () from /usr/local/lib/node_modules/parcel/node_modules/lmdb-store/prebuilds/linux-arm64/node.abi102.node
#17 0x0000ffff85c613f0 in mdb_env_open () from /usr/local/lib/node_modules/parcel/node_modules/lmdb-store/prebuilds/linux-arm64/node.abi102.node
#18 0x0000ffff85c613f0 in mdb_env_open () from /usr/local/lib/node_modules/parcel/node_modules/lmdb-store/prebuilds/linux-arm64/node.abi102.node
#19 0x0000ffff85c613f0 in mdb_env_open () from /usr/local/lib/node_modules/parcel/node_modules/lmdb-store/prebuilds/linux-arm64/node.abi102.node
#20 0x0000ffff85c613f0 in mdb_env_open () from /usr/local/lib/node_modules/parcel/node_modules/lmdb-store/prebuilds/linux-arm64/node.abi102.node
#21 0x0000ffff85c613f0 in mdb_env_open () from /usr/local/lib/node_modules/parcel/node_modules/lmdb-store/prebuilds/linux-arm64/node.abi102.node
```

## 💁 Possible Solution

Possibly the prebuilt binary isn't M1 compatible.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1 |
| Node             | v17.2.0 |
| npm/Yarn         | 8.1.4|
| Operating System | Alpine|

**Comment by plynchnlm** [comment]
I am also seeing segfaults, but when running parcel build on RHEL 7.  The build produces usable and working files, but then instead of a normal exit it segfaults.

**Comment by dreki** [comment]
I'm experiencing this as well.

My `Dockerfile` is based on: `FROM python:3.9-alpine3.14`

The project's `package.json` uses `"parcel": "^2.0.1"`.

Since this is a blocker, I'm going to just have to switch to something other than Parcel for now, unless someone knows of a workaround.

**Comment by devongovett** [comment]
Please try the nightly. I fixed some seg faults recently

**Comment by artvi** [comment]
I had a little journey trying to make parcel work within a docker container on m1 mac. First of all, I tried to migrate an existing project from v1 to v2 (`2.0.1`), but when I ran `yarn build index.html` I had this segfault error. The binary seemed to work partially since I was able to run `yarn parcel --help` and `yarn parcel --version`. Also tried `parcel@2.0.0-nightly.949` and `parcel@2.0.0-nightly.951` versions without any luck.
After experimenting with project changes, I started trying to make it work inside a container for a new empty project which was set as described at https://parceljs.org/getting-started/webapp/
Finally I was able to run `parcel build` successfully within `node:12.7-alpine3.12` image from https://hub.docker.com/_/node (no luck with `arm64v8/node` containers)
I also set up a new project inside Ubuntu Arm virtual machine and built it without any issues both with 16 and 17 node versions.
`uname -m` output inside every container I ran and inside Ubuntu vm was `aarch64`

**Comment by sethsamuel** [comment]
> Please try the nightly. I fixed some seg faults recently

Still getting segmentation fault with the above Dockerfile and `parcel@2.0.0-nightly.957+13649c36`

**Comment by sethsamuel** [comment]
Segfaults are fixed as of 2.2.1 for base parcel, but now having a problem with parcel-image:

```
Error: Error relocating
/app/node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node:
__crc32w: symbol not found
```

This still occurs on 2.0.0-nightly.984.

**Comment by samarth-sparrow** [comment]
FYI, we're seeing the same issue as @sethsamuel.  We were initially seeing segfaults when trying to run on M1 macs, and now encountering the same error.

Any updates or known workarounds here?

**Comment by plynchnlm** [comment]
Does it help to set the environment variable ```PARCEL_WORKER_BACKEND=process``` ?

**Comment by sethsamuel** [comment]
On 2.2.1 setting that env var doesn't have any affect. If I upgrade to 2.3.2, I hit #7234 and can't test this issue.

**Comment by sethsamuel** [comment]
I was able to workaround the latest iteration of this issue by disabling the image optimizer, since we aren't using it, but for those who need it the crash is still occurring in 2.3.2 with or without `PARCEL_WORKER_BACKEND=process`

**Comment by miletbaker** [comment]
Still occurring in 2.4.1 with or without `PARCEL_WORKER_BACKEND=process` and like you I've also disabled image optimiser for now.

**Comment by intersides** [comment]
/node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node:
 __crc32w: symbol not found

any update on this ?

**Comment by simlated** [comment]
Still happening with:

Host: Apple M1 Mac Monterey
Parcel: 2.7.0
Container from: node:18-alpine3.16 
Docker version 20.10.17, build 100c701

I'm going to use node:18-slim, can't find any solution to the issue :-(

**Comment by codemaster138** [comment]
FYI, I'm on parcel 2.7.0 (building from `node:16-alpine`) and still getting segfaults

**Comment by alshdavid** [comment]
Trying to recreate this

I'm on an M1 MacBook running docker 20.10.20, installing Parcel version 2.8.0. Building the image with docker and running the parcel CLI against a project mounted in a volume works without issue.

Command list
```bash
# Environment details
uname -mor

# Create Dockerfile
echo "FROM node:alpine" > dockerfile
echo "RUN apk add --no-cache build-base python3 && apk add --no-cache gcc g++" >> dockerfile
echo "RUN npm i -g parcel" >> dockerfile
echo "CMD parcel" >> dockerfile

# Build image
docker build -t parcel-cli .
docker run --rm -v $PWD:/app -w /app parcel-cli parcel --version

# Create bundle and build it
echo "console.log('foo')" > index.js
docker run --rm -v $PWD:/app -w /app parcel-cli parcel build index.js

# Output
ls
```

Result
```
$ uname -mor
Darwin 22.1.0 arm64

$ echo "FROM node:alpine" > dockerfile
$ echo "RUN apk add --no-cache build-base python3 && apk add --no-cache gcc g++" >> dockerfile
$ echo "RUN npm i -g parcel" >> dockerfile
$ echo "CMD parcel" >> dockerfile

$ docker build -t parcel-cli .
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM node:alpine
 ---> 13abfa428daf
Step 2/4 : RUN apk add --no-cache build-base python3 &&     apk add --no-cache gcc g++  
[ ... redacted ]
Successfully built cc6ac558e5f2
Successfully tagged parcel-cli:latest

$ docker run --rm -v $PWD:/app -w /app parcel-cli parcel --version
2.8.0

$ echo "console.log('foo')" > index.js

$ docker run --rm -v $PWD:/app -w /app parcel-cli parcel build index.js
^[[55;214RBuilding...
Bundling...
Packaging & Optimizing...
✨ Built in 565ms

dist/index.js    54 B    71ms;214Rll

$ ls
dist  dockerfile  index.js

$ ls dist
index.js  index.js.map

$ node dist/index.js
foo
```

I also tried this on a `linux-arm64` VM and it also worked fine

**Comment by drmax24** [comment]
FROM node:18.12.1-alpine3.16
...
Parcel 2.8
...

#87 35.81 /app/node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: 
#87 35.81 __crc32w: symbol not found

**Comment by geoynomous** [comment]
@drmax24  Same FROM - during `parcel build` inside the Dockerfile - during `docker build` - same symbol not found

```
#42 32.18 Error: Error relocating 
#42 32.18 /project/clients/frontends/node_modules/.pnpm/@parcel+optimizer-image@2.8.0_@parcel+core@2.8.0/node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node:
#42 32.18  __crc32w: symbol not found
#42 32.18 
#42 32.18   Error: Error relocating 
#42 32.18   /proeject/clients/frontends/node_modules/.pnpm/@parcel+optimizer-image@2.8.0_@parcel+core@2.8.0/node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node:
#42 32.18    __crc32w: symbol not found
```

And also tried node:18.12.1-alpine3.17 - same there

`parcel build` OUTSIDE the `docker build` on the zsh works perfect on Silicon

**Comment by lorenzogrv** [comment]
I'm commenting here because #8790 is closed by @mischnic, instructing to follow here.

After resolving a failing build on ARM64 Graviton2 caused by huge memory usage (see comment at #5072), we had "the symbol not found" error as stated before.

```plain
node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: __crc32w: symbol not found
```

Disabling image optimization works-around the issue, but of course is not desired as permanent. It smells like something is wrong with the parcel arm64-musl build. After some research, I've found an [interesting QA on SO](https://stackoverflow.com/a/46251637/1894803):

> Q: **Does Clang lack CRC32 for ARMv8/Aarch64?**
>
> A:
> (...)
> According to [ARM's document][2] ("ARM® Architecture Reference Manual
> ARMv8, for ARMv8-A architecture profile" DDI0487B_a_armv8_arm.pdf: page A1-58), crc32 instructions are optional for v8 and mandatory for v8.1. 
> (...)

For me, it seems some [ARM flag is need at compile time][1]. I would like to dive into, but would help some guidance about parcel's internals so I can compile optimizer-image by my own means. Are there any docs where I can research further?

[1]: https://gcc.gnu.org/onlinedocs/gcc-7.2.0/gcc/ARM-Options.html
[2]: https://developer.arm.com/docs/ddi0487/latest/arm-architecture-reference-manual-armv8-for-armv8-a-architecture-profile

**Comment by mischnic** [comment]
@lorenzogrv
Clone the repo, run `yarn` in the root, go into this directory https://github.com/parcel-bundler/parcel/tree/v2/packages/optimizers/image, and run `yarn build` or `yarn build-release`. That will create the file `parcel-image.darwin-x64.node` (or whatever target you're on).

The `napi` CLI will internally call `cargo build` (or some version of that), so you'll need to figure out how to set these ARM flags for Rust. Maybe something like https://rust-lang.github.io/packed_simd/perf-guide/target-feature/rustflags.html
If you have figured out what has to be set, we can see how to set that flag conditionally only on ARM.

**Comment by lorenzogrv** [comment]
I dived a bit today.

I could setup a dev environment for amd64 following your tips with success, but still need to figure out how to set up some of your dependencies within the native arm64 environment.

Sharing here the build PoC I've used for future visitors. Infra summary (`docker buildx ls`):

```plain
NAME/NODE DRIVER/ENDPOINT         STATUS  BUILDKIT PLATFORMS
buildx *  docker-container                              
  buildx0 unix:///var/run/docker.sock  running v0.11.2  linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/386
  buildx1 ssh://[MASKED]                        running v0.11.2  linux/arm64*, linux/arm/v7, linux/arm/v6
default   docker                                        
  default default                                       running 20.10.22 linux/amd64, linux/386
```

<details>
  <summary>Dockerfile</summary>

```Dockerfile
##
# This is a Poc to dive into
# https://github.com/parcel-bundler/parcel/issues/7402
##

# https://hub.docker.com/_/rust
FROM rust:alpine3.16 AS parcel

RUN apk add git \
    && git clone https://github.com/parcel-bundler/parcel.git /parcel

WORKDIR /parcel
RUN apk add \
        nodejs yarn \
        # musl-dev is needed to compile some dependencies (any arch) \
        musl-dev \
        # python3 is needed under aarch64 for node-gyp-build \
        python3 \
    && yarn

WORKDIR /parcel/packages/optimizers/image
RUN yarn build \
    && ls -lha
```

</details>

Build log from `docker build --progress=plain --platform arm64 .` (Note: buildx as default build engine)

<details>
  <summary>Build log</summary>

```plain
#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 30B 0.1s
#1 transferring dockerfile: 594B 0.2s done
#1 DONE 0.2s

#2 [internal] load .dockerignore
#2 transferring context: 2B 0.1s done
#2 DONE 0.1s

#3 [internal] load metadata for docker.io/library/rust:alpine3.16
#3 DONE 0.3s

#4 [1/6] FROM docker.io/library/rust:alpine3.16@sha256:d1bebf89ffa8cdb3b875afd86cede2e1caa2d16016c79d3b5fb8315269033480
#4 resolve docker.io/library/rust:alpine3.16@sha256:d1bebf89ffa8cdb3b875afd86cede2e1caa2d16016c79d3b5fb8315269033480 0.0s done
#4 DONE 0.0s

#4 [1/6] FROM docker.io/library/rust:alpine3.16@sha256:d1bebf89ffa8cdb3b875afd86cede2e1caa2d16016c79d3b5fb8315269033480
#4 sha256:befa2d850f56780dbf5acaa28401b4cbdfcd9a79bdb253f15426e304967a3d28 6.29MB / 223.69MB 0.2s
#4 sha256:befa2d850f56780dbf5acaa28401b4cbdfcd9a79bdb253f15426e304967a3d28 17.83MB / 223.69MB 0.3s
#4 sha256:befa2d850f56780dbf5acaa28401b4cbdfcd9a79bdb253f15426e304967a3d28 33.55MB / 223.69MB 0.5s
#4 sha256:befa2d850f56780dbf5acaa28401b4cbdfcd9a79bdb253f15426e304967a3d28 49.28MB / 223.69MB 0.6s
#4 sha256:befa2d850f56780dbf5acaa28401b4cbdfcd9a79bdb253f15426e304967a3d28 69.21MB / 223.69MB 0.8s
#4 sha256:befa2d850f56780dbf5acaa28401b4cbdfcd9a79bdb253f15426e304967a3d28 91.23MB / 223.69MB 0.9s
#4 sha256:befa2d850f56780dbf5acaa28401b4cbdfcd9a79bdb253f15426e304967a3d28 116.39MB / 223.69MB 1.1s
#4 sha256:befa2d850f56780dbf5acaa28401b4cbdfcd9a79bdb253f15426e304967a3d28 138.41MB / 223.69MB 1.2s
#4 sha256:befa2d850f56780dbf5acaa28401b4cbdfcd9a79bdb253f15426e304967a3d28 158.33MB / 223.69MB 1.4s
#4 sha256:befa2d850f56780dbf5acaa28401b4cbdfcd9a79bdb253f15426e304967a3d28 182.45MB / 223.69MB 1.5s
#4 sha256:befa2d850f56780dbf5acaa28401b4cbdfcd9a79bdb253f15426e304967a3d28 200.28MB / 223.69MB 1.7s
#4 sha256:befa2d850f56780dbf5acaa28401b4cbdfcd9a79bdb253f15426e304967a3d28 223.69MB / 223.69MB 2.0s
#4 sha256:befa2d850f56780dbf5acaa28401b4cbdfcd9a79bdb253f15426e304967a3d28 223.69MB / 223.69MB 2.2s done
#4 extracting sha256:befa2d850f56780dbf5acaa28401b4cbdfcd9a79bdb253f15426e304967a3d28
#4 extracting sha256:befa2d850f56780dbf5acaa28401b4cbdfcd9a79bdb253f15426e304967a3d28 3.6s done
#4 DONE 5.9s

#5 [2/6] RUN apk add git     && git clone https://github.com/parcel-bundler/parcel.git /parcel
#5 0.437 fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/aarch64/APKINDEX.tar.gz
#5 0.538 fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/aarch64/APKINDEX.tar.gz
#5 0.790 (1/6) Installing brotli-libs (1.0.9-r6)
#5 0.800 (2/6) Installing nghttp2-libs (1.47.0-r0)
#5 0.804 (3/6) Installing libcurl (7.83.1-r5)
#5 0.811 (4/6) Installing expat (2.5.0-r0)
#5 0.816 (5/6) Installing pcre2 (10.40-r0)
#5 0.822 (6/6) Installing git (2.36.4-r0)
#5 0.927 Executing busybox-1.35.0-r17.trigger
#5 0.939 OK: 119 MiB in 31 packages
#5 0.988 Cloning into '/parcel'...
#5 DONE 7.0s

#6 [3/6] WORKDIR /parcel
#6 DONE 0.1s

#7 [4/6] RUN apk add         nodejs yarn         musl-dev         python3     && yarn
#7 0.294 (1/17) Upgrading musl (1.2.3-r1 -> 1.2.3-r2)
#7 0.337 (2/17) Installing musl-dev (1.2.3-r2)
#7 0.404 (3/17) Installing c-ares (1.18.1-r0)
#7 0.409 (4/17) Installing icu-data-en (71.1-r2)
#7 0.427 Executing icu-data-en-71.1-r2.post-install
#7 0.429 *
#7 0.429 * If you need ICU with non-English locales and legacy charset support, install
#7 0.429 * package icu-data-full.
#7 0.429 *
#7 0.430 (5/17) Installing icu-libs (71.1-r2)
#7 0.462 (6/17) Installing nodejs (16.17.1-r0)
#7 0.653 (7/17) Installing libbz2 (1.0.8-r1)
#7 0.656 (8/17) Installing libffi (3.4.2-r1)
#7 0.659 (9/17) Installing gdbm (1.23-r0)
#7 0.662 (10/17) Installing xz-libs (5.2.5-r1)
#7 0.666 (11/17) Installing mpdecimal (2.5.1-r1)
#7 0.671 (12/17) Installing ncurses-terminfo-base (6.3_p20220521-r0)
#7 0.678 (13/17) Installing ncurses-libs (6.3_p20220521-r0)
#7 0.685 (14/17) Installing readline (8.1.2-r0)
#7 0.690 (15/17) Installing sqlite-libs (3.38.5-r0)
#7 0.701 (16/17) Installing python3 (3.10.9-r0)
#7 1.114 (17/17) Installing yarn (1.22.19-r0)
#7 1.143 Executing busybox-1.35.0-r17.trigger
#7 1.149 OK: 224 MiB in 47 packages
#7 1.561 yarn install v1.22.19
#7 1.840 [1/5] Validating package.json...
#7 1.963 [2/5] Resolving packages...
#7 2.972 [3/5] Fetching packages...
#7 36.58 warning parcel-for-vscode@2.8.3: The engine "vscode" appears to be invalid.
#7 36.58 warning vscode-languageclient@8.0.2: The engine "vscode" appears to be invalid.
#7 36.59 [4/5] Linking dependencies...
#7 36.61 warning " > @parcel/transformer-elm@2.8.3" has unmet peer dependency "elm@^0.19.1-5".
#7 36.61 warning " > @parcel/transformer-mdx@2.8.3" has unmet peer dependency "@mdx-js/react@^1.6.22".
#7 36.61 warning " > @parcel/transformer-typescript-tsc@2.8.3" has unmet peer dependency "typescript@>=3.0.0".
#7 36.61 warning " > @parcel/transformer-typescript-types@2.8.3" has unmet peer dependency "typescript@>=3.0.0".
#7 36.61 warning " > @parcel/ts-utils@2.8.3" has unmet peer dependency "typescript@>=3.0.0".
#7 36.61 warning " > @parcel/validator-eslint@2.8.3" has incorrect peer dependency "eslint@^6.0.0".
#7 36.61 warning " > @parcel/validator-typescript@2.8.3" has unmet peer dependency "typescript@>=3.0.0".
#7 59.91 [5/5] Building fresh packages...
#7 61.22 error /parcel/node_modules/elm: Command failed.
#7 61.22 Exit code: 1
#7 61.22 Command: node install.js
#7 61.22 Arguments: 
#7 61.22 Directory: /parcel/node_modules/elm
#7 61.22 Output:
#7 61.22 -- ERROR -----------------------------------------------------------------------
#7 61.22 
#7 61.22 I am detecting that your computer (linux_arm64) may not be compatible with any
#7 61.22 of the official pre-built binaries.
#7 61.22 
#7 61.22 I recommend against using the npm installer for your situation. Check out the
#7 61.22 alternative installers at https://github.com/elm/compiler/releases/tag/0.19.1
#7 61.22 to see if there is something that will work better for you.
#7 61.22 
#7 61.22 From there I recommend asking for guidance on Slack or Discourse to find someone
#7 61.22 who can help with your specific situation.
#7 61.22 
#7 61.22 --------------------------------------------------------------------------------
#7 61.22 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
#7 ERROR: process "/bin/sh -c apk add         nodejs yarn         musl-dev         python3     && yarn" did not complete successfully: exit code: 1
------
 > [4/6] RUN apk add         nodejs yarn         musl-dev         python3     && yarn:
#7 61.22 
#7 61.22 I recommend against using the npm installer for your situation. Check out the
#7 61.22 alternative installers at https://github.com/elm/compiler/releases/tag/0.19.1
#7 61.22 to see if there is something that will work better for you.
#7 61.22 
#7 61.22 From there I recommend asking for guidance on Slack or Discourse to find someone
#7 61.22 who can help with your specific situation.
#7 61.22 
#7 61.22 --------------------------------------------------------------------------------
#7 61.22 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
Dockerfile:13
--------------------
  12 |     WORKDIR /parcel
  13 | >>> RUN apk add \
  14 | >>>         nodejs yarn \
  15 | >>>         # musl-dev is needed to compile some dependencies (any arch) \
  16 | >>>         musl-dev \
  17 | >>>         # python3 is needed under aarch64 for node-gyp-build \
  18 | >>>         python3 \
  19 | >>>     && yarn
  20 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c apk add         nodejs yarn         musl-dev         python3     && yarn" did not complete successfully: exit code: 1
```

</details>

**Comment by lorenzogrv** [comment]
@mischnic  Please reopen. Did not have time to dive more

**Comment by molind** [comment]
It's dynamically depends on some libs. 

```
/app # ldd node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node 
	/lib/ld-musl-aarch64.so.1 (0xffff89b2d000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0xffff899bb000)
	libc.so => /lib/ld-musl-aarch64.so.1 (0xffff89b2d000)
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_get_global: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_get_value_string_utf8: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: __crc32w: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_get_cb_info: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_create_object: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_get_undefined: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_create_buffer: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_call_threadsafe_function: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_set_named_property: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_get_named_property: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_coerce_to_string: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_create_error: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_create_buffer_copy: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_create_external_buffer: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: __crc32d: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: __crc32b: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: __crc32h: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_get_buffer_info: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_add_env_cleanup_hook: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_throw_error: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_typeof: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_delete_reference: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_call_function: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: __crc32cw: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_create_string_utf8: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_throw: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_create_function: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_get_reference_value: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_get_and_clear_last_exception: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_define_class: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_create_threadsafe_function: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_create_reference: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_reference_unref: symbol not found
Error relocating node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node: napi_unref_threadsafe_function: symbol not found
```
