### ISSUE TITLE
Parcel adds import of process in browser context

### ISSUE THREAD

**Issue by F30** [parcel-bundler/parcel#7877]
# 🐛 Bug Report

Consider a piece of code accessing the `process` global, e.g. this one:

```
// src/index.js

export function detectNode() {
  if (typeof process !== "undefined" && process.release.name === "node") {
    console.log("We are in Node")
  }
}
```

We use Parcel to build a library from it like this:

```
"targets": {
  "default": {
    "source": "src/index.js",
    "isLibrary": true,
    "context": "browser",
    "outputFormat": "esmodule"
  }
}
```

This results in a target file with a line like:

```
import * as $bWGXq$process from "process";
```

However, `process` cannot be imported in browsers.

The same thing happens with `context`s `"web-worker"`, `"service-worker"` etc. However, the import is gone with `"context": "node"`!

## 🎛 Configuration
"package.json":
```
{
  "name": "parcel-demo",
  "devDependencies": {
    "parcel": "^2.4.0"
  },
  "targets": {
    "default": {
      "source": "src/index.js",
      "isLibrary": true,
      "context": "browser",
      "outputFormat": "esmodule"
    }
  }
}
```

CLI command: `npx parcel build`

## 🤔 Expected Behavior
Parcel should not add imports to globals that are unavailable in the target's execution context.

## 💁 Possible Solution
Shouldn't it behave the other way round (import for Node, no import for browsers)? 🤔

## 🌍 Your Environment
| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.4.0 |
| Node             | 17.6.0 |
| npm/Yarn         | npm 8.5.1 |
| Operating System | Debian 11 |

**Comment by mischnic** [comment]
Parcel polyfills various global variables that exist in Node. Among those is `process`. So for a Node build, nothing is done because that variable will be available. But some npm modules use it.

So you should be using `process.browser` to determine if you're in the browser (and that shouldn't cause the `process` to get imported).

**Comment by F30** [comment]
Thanks for your quick response.

> Parcel polyfills various global variables that exist in Node. Among those is `process`.

OK, but where is the browser supposed to get the polyfill from? From my understanding and experience, it won't know how to handle `import from "process"`.

> So for a Node build, nothing is done because that variable will be available.

It will be available as a global, but in fact Node [recommends to explicitly import it](https://nodejs.org/api/process.html#process). In fact, that is the case where I would expect `import from "process"` to work.

> So you should be using `process.browser` to determine if you're in the browser (and that shouldn't cause the `process` to get imported).

The code from above might not be ideal, but some shenanigans around `process` are in fact [a common way](https://stackoverflow.com/a/35813135) to check for Node vs. browser. In my real-world case, I have little influence on it, since it is a third-party library that accesses `process`.

**Comment by mischnic** [comment]
> OK, but where is the browser supposed to get the polyfill from? From my understanding and experience, it won't know how to handle import from "process".

You're specifying `"isLibrary": true,`, so the output is intended to be consumed by bundlers (e.g. to be published to npm), not by browsers.

> It will be available as a global, but in fact Node [recommends to explicitly import it](https://nodejs.org/api/process.html#process).

There are many (legacy) npm packages not importing it.

**Comment by devongovett** [comment]
I think this was answered. Remove isLibrary if you are consuming the result directly in the browser, and not running it through another bundler.

**Comment by F30** [comment]
> You're specifying `"isLibrary": true,`, so the output is intended to be consumed by bundlers (e.g. to be published to npm), not by browsers.

Hmm, that does make sense. On the other hand, modern browsers do natively support ES modules, so I wouldn't consider `isLibrary` to be synonymous to "consumed by a bundler".

In my specific case, I am building a library exposing all functions used by test cases. It gets loaded in a browser parallel to the testing code (using [jasmine-browser-runner](https://jasmine.github.io/setup/browser.html)).

I cannot build this with `"isLibrary": false`, because that eliminates all unused (but exported) functions. I cannot build this with `"isLibrary": true, "context": "browser"`, because that adds an import of `process`. The only combination that works is `"isLibrary": true, "context": "node"`, though apparently only by accident.

> There are many (legacy) npm packages not importing it.

Fair enough.

**Comment by multivoltage** [comment]
@F30 , how did you sole it?

**Comment by F30** [comment]
@multivoltage: For my specific problem, I ended up using `"outputFormat": "global"` and "exporting" the functions as properties of `window`. This way, they can be accessed from other scripts in the browser without using a module system. At least until #7240 has been merged, defining properties of `window` appears to be [the common way](https://stackoverflow.com/q/64429055) to declare global variables.

**Comment by GillesTourreau** [comment]
@F30 and @multivoltage, I fixed the issue by defining an alias in the `package.json` file:

```json
"alias": {
  "process": false,
  "buffer": false
},
```

Related to the the issue #7697.

**Comment by OdapX** [comment]
That didn't solve it for me. I ended up making a custom resolver to override the paths. 

```import { Resolver } from '@parcel/plugin';
import path from 'path';
const __dirname = path.resolve(path.dirname(''));
// eslint-disable-next-line import/no-anonymous-default-export
export default new Resolver({
  async resolve({ specifier }) {
    if (specifier === 'process') {
      return {
        filePath: path.join(__dirname, '/path_to/process.js'),
      };
    }
    if (specifier === 'buffer') {
      return {
        filePath: path.join(__dirname, '/path_to/buffer.js'),
      };
    }
    return null;
  },
});
```
 buffer.js:
```
export const Buffer = {};
```
process.js:
```
export default {}
```

and I used it inside my .parcelrc like this:
```
{
  "extends": "@parcel/config-default",
  "resolvers": ["parcel-resolver-emulate-packages", "@parcel/resolver-default"]
}
```

NB: you need to publish the resolver or link it locally.  you can otherwise install parcel-resolver-emulate-packages to test.
