### ISSUE TITLE
`Uncaught SyntaxError: Unexpected token ')'` in watch mode

### ISSUE THREAD

**Issue by jtojnar** [parcel-bundler/parcel#7916]
# 🐛 bug report

When I try to build a module depending on `netlify-cms` using `parcel`, I get the following error:

```
Uncaught SyntaxError: Unexpected token ')' (at index.b379fa61.js:135076:47)
```

It seems to work when building using `parcel build`.

## 🎛 Configuration (.babelrc, package.json, cli command)

Building with `npx parcel admin/index.html --dist-dir public/admin/ --public-url .`

No special configuration, see the [minimal example](https://github.com/jtojnar/repro/tree/738c2d442b504378b145edde2fdc52c8b2e217a0/parcel-netlify-cms).

## 🤔 Expected Behavior

The code should be produced without error.

## 😯 Current Behavior

Viewing the generated file in Firefox or Chromium reveals a syntax error.

## 🔦 Context

The line points to the following code:

```javascript
function oe() {
    var e, t, n, r = 35 * G + 0, o = Z[r];
    if (o) return G = o.nextPos, o.result;
    for(e = G, t = [], n = ae(); n !== i674;)t.push(n), n = ae();
    return t !== i674 && (), e = t, Z[r] = {
    //                   ^
    // It’s these parens causing the error.
        nextPos: G,
        result: e
    }, e;
}
```

For some reason neither Chromium nor Firefox seems to use the source maps for this so I cannot determine the original source code.

## 💻 Code Sample

https://github.com/jtojnar/repro/tree/738c2d442b504378b145edde2fdc52c8b2e217a0/parcel-netlify-cms

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.4.1
| Node             |16.14.2
| npm/Yarn         |8.5.0
| Operating System |NixOS

**Comment by devongovett** [comment]
Possibly fixed by https://github.com/parcel-bundler/parcel/pull/7886, which hasn't been released yet. You could try the latest nightly version and see if that fixes it?

**Comment by jtojnar** [comment]
I can still reproduce this on [2.0.0-nightly.1039+211502e55](https://github.com/parcel-bundler/parcel/commit/211502e55472749056fae132c3810fa6edfdade4).

**Comment by devongovett** [comment]
Original code (from https://unpkg.com/netlify-cms@2.10.190/dist/cms.js):

```js
function oe() {
    var e, t, n, r = 35 * G + 0,
        o = Z[r];
    if (o) return G = o.nextPos, o.result;
    for (e = G, t = [], n = ae(); n !== i;) t.push(n), n = ae();
    return t !== i && (e, t = t), e = t, Z[r] = {
        nextPos: G,
        result: e
    }, e
}
```

Probably due to:

https://github.com/parcel-bundler/parcel/blob/211502e55472749056fae132c3810fa6edfdade4/packages/transformers/js/core/src/lib.rs#L344-L348

Should the `paren_remover` be after the expr simplifier? cc. @mischnic

**Comment by mischnic** [comment]
As far as I understand it, `paren_remover` doesn't actually remove comments, it just attaches the comments correctly so that they doesn't get removed. https://github.com/swc-project/swc/issues/3115#issuecomment-1068409981

Also, this is caused by the `dead_branch_remover`: https://github.com/swc-project/swc/issues/4272
